/*
 * Copyright 2026 NWChemEx-Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
#include <chemist/experimental/basis_set/cartesian_ao_view.hpp>
#include <chemist/experimental/basis_set/contracted_gaussian_view.hpp>
#include <chemist/experimental/basis_set/spherical_ao_view.hpp>
#include <chemist/experimental/traits/cca_shell_traits.hpp>
#include <cstddef>
#include <memory>
#include <stdexcept>
#include <string>
#include <type_traits>

namespace chemist::experimental {

/** @brief Implements the API shared by CCAShell and CCAShellView.
 *
 *  A CCA shell is a shell whose AOs are enumerated in the Common Component
 *  Architecture ordering, which is what libint2 calls its *standard*
 *  ordering. Per docs/source/developer/design/basis_set/ao_hierarchy.rst:
 *
 *  - a Cartesian CCA shell is generated by letting @f$i@f$ run from
 *    @f$\ell@f$ down to zero and, within each @f$i@f$, letting @f$j@f$ run
 *    from @f$\ell - i@f$ down to zero, e.g.
 *    @f$\ell = 2:\; xx, xy, xz, yy, yz, zz@f$;
 *  - a pure CCA shell runs @f$m_\ell@f$ from @f$-\ell@f$ to @f$+\ell@f$.
 *
 *  All of a shell's state is its one contracted Gaussian --- @f$\ell@f$ and
 *  the center included --- whatever its purity. A pure shell is built on the
 *  Cartesian shell of that contracted Gaussian, which *this presents as a view
 *  (get_cartesian_shell) rather than storing, so there is still exactly one
 *  contracted Gaussian per shell. As a result *this needs only one hook from
 *  the derived class, for either purity.
 *
 *  Exactly like CartesianAOCommon, *this is a plain CRTP mixin and does not
 *  itself derive from AOShell or AOShellView; the concrete classes pick up one
 *  of those.
 *
 *  @tparam DerivedType The class deriving from *this. Must define
 *                      `contracted_gaussian_()` and declare *this a friend.
 *  @tparam ShellType The, possibly const-qualified, CCAShell<AOType> the
 *                    derived class models. Its AO type decides the purity,
 *                    and its const-qualification whether the setters exist.
 */
template<typename DerivedType, typename ShellType>
class CCAShellCommon {
private:
    /// Struct defining the types for the shell *this acts like
    using traits_type = ChemistClassTraits<ShellType>;

    /// Enables a method only when *this can mutate the aliased state
    template<typename U, typename ReturnType = void>
    using enable_if_mutable_t =
      std::enable_if_t<!std::is_const_v<U>, ReturnType>;

    /// Enables a method only when the shell modeled by U is Cartesian
    template<typename U, typename ReturnType>
    using enable_if_cartesian_t =
      std::enable_if_t<!ChemistClassTraits<U>::is_pure, ReturnType>;

    /// Enables a method only when the shell modeled by U is pure
    template<typename U, typename ReturnType>
    using enable_if_pure_t =
      std::enable_if_t<ChemistClassTraits<U>::is_pure, ReturnType>;

public:
    /// Type of the shell *this acts like
    using value_type = typename traits_type::value_type;

    /// Type of the AOs in *this
    using ao_type = typename traits_type::ao_type;

    /// Type of a read-only view of one of the AOs in *this
    using const_ao_reference = typename traits_type::const_ao_reference;

    /// Type of a pointer to a read-only view of one of the AOs in *this
    using const_ao_pointer = typename traits_type::const_ao_pointer;

    /// Type of a read-only view of the Cartesian shell underneath *this
    using const_cartesian_shell_reference =
      typename traits_type::const_cartesian_shell_reference;

    /// Type used to model the total angular momentum
    using angular_momentum_type = typename traits_type::angular_momentum_type;

    /// Type used to model one Cartesian power
    using angular_index_type = typename traits_type::angular_index_type;

    /// Type holding the powers @f$(i,j,k)@f$ of one Cartesian AO
    using cartesian_powers_type = typename traits_type::cartesian_powers_type;

    /// Type used to model the component, @f$m_\ell@f$, of one spherical AO
    using magnetic_index_type = typename traits_type::magnetic_index_type;

    /// Type of the contracted Gaussian *this is built on
    using contracted_gaussian_type =
      typename traits_type::contracted_gaussian_type;

    /// Type of a, possibly mutable, aliasing view of the contracted Gaussian
    using contracted_gaussian_reference =
      typename traits_type::contracted_gaussian_reference;

    /// Type of a read-only, aliasing view of the contracted Gaussian
    using const_contracted_gaussian_reference =
      typename traits_type::const_contracted_gaussian_reference;

    /// Type of a read-only view of a Cartesian AO built on the contracted
    /// Gaussian
    using const_cartesian_ao_reference =
      typename traits_type::const_cartesian_ao_reference;

    /// Type used to model the point *this is centered on
    using center_type = typename traits_type::center_type;

    /// Type of a read-only, aliasing view of the center
    using const_center_reference = typename traits_type::const_center_reference;

    /// Type *this uses to model a single Cartesian coordinate
    using coord_type = typename traits_type::coord_type;

    /// Type of a normalization constant
    using numerical_value = coord_type;

    /// Type used for indexing and offsets
    using size_type = std::size_t;

    // -------------------------------------------------------------------------
    // -- Accessors
    // -------------------------------------------------------------------------

    /** @brief Returns the total angular momentum shared by the AOs in *this.
     *
     *  This is the angular momentum of the contracted Gaussian; *this does not
     *  store a second copy.
     *
     *  @throw None No throw guarantee.
     */
    angular_momentum_type get_l() const {
        return get_contracted_gaussian().get_l();
    }

    /** @brief Is *this a pure (spherical) shell?
     *
     *  For a CCA shell this is decided by its type: CCAShell<SphericalAO> is
     *  pure and CCAShell<CartesianAO> is not.
     *
     *  @throw None No throw guarantee.
     */
    constexpr bool is_pure() const noexcept { return traits_type::is_pure; }

    /** @brief Is *this a Cartesian shell?
     *
     *  This is a convenience for `!is_pure()`.
     *
     *  @throw None No throw guarantee.
     */
    constexpr bool is_cartesian() const noexcept { return !is_pure(); }

    /** @brief Returns the number of AOs in *this.
     *
     *  @f$2\ell+1@f$ for a pure shell and @f$(\ell+1)(\ell+2)/2@f$ for a
     *  Cartesian one.
     *
     *  @throw None No throw guarantee.
     */
    size_type size() const {
        const auto l = get_l();
        return is_pure() ? 2 * l + 1 : (l + 1) * (l + 2) / 2;
    }

    /** @brief Returns the contracted Gaussian every AO in *this is built on.
     *
     *  The returned view aliases the one contracted Gaussian *this owns or
     *  aliases, so writing through it (when *this models a mutable shell)
     *  changes every AO in *this.
     *
     *  @throw None No throw guarantee.
     */
    ///@{
    contracted_gaussian_reference get_contracted_gaussian() {
        return downcast_().contracted_gaussian_();
    }

    const_contracted_gaussian_reference get_contracted_gaussian() const {
        return downcast_().contracted_gaussian_();
    }
    ///@}

    /** @brief Returns the point *this is centered on.
     *
     *  Reached through the contracted Gaussian, rather than stored, for the
     *  reason given on CartesianAOCommon::get_center.
     *
     *  @throw None No throw guarantee.
     */
    const_center_reference get_center() const {
        return get_contracted_gaussian().get_center();
    }

    /** @brief Returns the Cartesian shell underneath *this.
     *
     *  For a pure shell this is the Cartesian shell its spherical AOs are
     *  linear combinations of. For a Cartesian shell it is *this, viewed as a
     *  read-only CCAShell<CartesianAO>. Either way the result is a view
     *  aliasing the contracted Gaussian of *this, not a copy.
     *
     *  @throw None No throw guarantee.
     */
    const_cartesian_shell_reference get_cartesian_shell() const {
        return const_cartesian_shell_reference(get_contracted_gaussian());
    }

    /** @brief Returns the Cartesian powers of the AO at offset @p i.
     *
     *  This is the Cartesian CCA ordering documented on *this. When *this is a
     *  pure shell this method does not participate in overload resolution.
     *
     *  @param[in] i The offset of the AO. Must be in [0, size()).
     *
     *  @return The powers of @f$x@f$, @f$y@f$, and @f$z@f$, in that order.
     *
     *  @throw std::out_of_range if @p i is not in [0, size()). Strong throw
     *                           guarantee.
     */
    template<typename U = ShellType>
    enable_if_cartesian_t<U, cartesian_powers_type> cartesian_powers(
      size_type i) const {
        check_offset_(i);
        const auto l = get_l();
        size_type offset{0};
        for(angular_index_type x = l + 1; x-- > 0;) {
            // With x fixed there are l - x + 1 AOs, one per y in [l-x, 0].
            const auto n_in_block = l - x + 1;
            if(i < offset + n_in_block) {
                const angular_index_type y = (l - x) - (i - offset);
                return cartesian_powers_type{x, y, l - x - y};
            }
            offset += n_in_block;
        }
        // Unreachable, since check_offset_ bounds i by the size of the shell
        throw std::logic_error(
          "chemist::experimental::CCAShell: ran off the end of the shell.");
    }

    /** @brief Returns the component, @f$m_\ell@f$, of the AO at offset @p i.
     *
     *  This is the pure CCA ordering, @f$m_\ell = i - \ell@f$. When *this is a
     *  Cartesian shell this method does not participate in overload
     *  resolution.
     *
     *  @param[in] i The offset of the AO. Must be in [0, size()).
     *
     *  @return The component of the AO at offset @p i.
     *
     *  @throw std::out_of_range if @p i is not in [0, size()). Strong throw
     *                           guarantee.
     */
    template<typename U = ShellType>
    enable_if_pure_t<U, magnetic_index_type> magnetic_index(size_type i) const {
        check_offset_(i);
        return static_cast<magnetic_index_type>(i) -
               static_cast<magnetic_index_type>(get_l());
    }

    /** @brief Returns the AO at offset @p i.
     *
     *  The result is a read-only view which aliases the state of *this: a
     *  CartesianAOView whose contracted Gaussian is *this's for a Cartesian
     *  shell, and a SphericalAOView of get_cartesian_shell() for a pure one.
     *  The view is built on demand and the caller owns the returned pointer,
     *  but since the view aliases *this it must not outlive *this.
     *
     *  The angular index of the view is fixed when it is built, so a view
     *  obtained before the angular momentum of *this changes no longer agrees
     *  with the contracted Gaussian it aliases; re-index *this instead.
     *
     *  @param[in] i The offset of the AO. Must be in [0, size()).
     *
     *  @return A pointer to a newly allocated, read-only view of the requested
     *          AO.
     *
     *  @throw std::out_of_range if @p i is not in [0, size()). Strong throw
     *                           guarantee.
     *  @throw std::bad_alloc if there is a problem allocating the view. Strong
     *                        throw guarantee.
     */
    const_ao_pointer at(size_type i) const {
        check_offset_(i);
        return std::make_unique<const_ao_reference>(make_ao_(i));
    }

    /// Same as at()
    const_ao_pointer operator[](size_type i) const { return at(i); }

    /** @brief Returns the normalization constant of *this, @f$N^{G}@f$.
     *
     *  See AOShellCommon::normalization_constant.
     *
     *  @throw std::runtime_error if the parameters of the contraction are not
     *                            all holding the same concrete floating-point
     *                            type. Strong throw guarantee.
     */
    numerical_value normalization_constant() const {
        return get_contracted_gaussian().normalization_constant();
    }

    // -------------------------------------------------------------------------
    // -- Setters
    // -------------------------------------------------------------------------

    /** @brief Sets the total angular momentum of *this.
     *
     *  This writes into the contracted Gaussian, so it changes the number of
     *  AOs in *this and every view aliasing the same contracted Gaussian
     *  observes it. AO views previously obtained from *this keep their old
     *  angular indices, and so no longer agree with the contracted Gaussian
     *  they alias; re-index *this after calling this.
     *
     *  When *this models a read-only shell this method does not participate
     *  in overload resolution.
     *
     *  @param[in] value The new total angular momentum.
     *
     *  @throw None No throw guarantee.
     */
    template<typename U = ShellType>
    enable_if_mutable_t<U> set_l(angular_momentum_type value) {
        get_contracted_gaussian().set_l(value);
    }

    // -------------------------------------------------------------------------
    // -- Utility
    // -------------------------------------------------------------------------

    /** @brief Determines if *this is value equal to @p rhs.
     *
     *  Two CCA shells are value equal if they have the same purity and their
     *  contracted Gaussians are value equal. The ordering is the type, so it
     *  can not differ. Whether either owns or aliases its contracted Gaussian
     *  is NOT considered.
     *
     *  @tparam OtherDerived The derived type of @p rhs.
     *  @tparam OtherShell The CCA shell type @p rhs models.
     *
     *  @param[in] rhs The shell to compare to *this.
     *
     *  @return True if *this is value equal to @p rhs and false otherwise.
     *
     *  @throw None No throw guarantee.
     */
    template<typename OtherDerived, typename OtherShell>
    bool operator==(
      const CCAShellCommon<OtherDerived, OtherShell>& rhs) const noexcept {
        return is_pure() == rhs.is_pure() &&
               get_contracted_gaussian() == rhs.get_contracted_gaussian();
    }

    /** @brief Determines if *this differs from @p rhs.
     *
     *  This method defines "different" as not value equal. See operator== for
     *  the definition of value equal.
     */
    template<typename OtherDerived, typename OtherShell>
    bool operator!=(
      const CCAShellCommon<OtherDerived, OtherShell>& rhs) const noexcept {
        return !((*this) == rhs);
    }

protected:
    /// Only the derived class should be creating/copying *this
    ///@{
    CCAShellCommon() noexcept                                 = default;
    CCAShellCommon(const CCAShellCommon&) noexcept            = default;
    CCAShellCommon(CCAShellCommon&&) noexcept                 = default;
    CCAShellCommon& operator=(const CCAShellCommon&) noexcept = default;
    CCAShellCommon& operator=(CCAShellCommon&&) noexcept      = default;
    ~CCAShellCommon() noexcept                                = default;
    ///@}

private:
    /// Builds the view of the AO at offset @p i. The offset is not checked.
    const_ao_reference make_ao_(size_type i) const {
        if constexpr(traits_type::is_pure) {
            return const_ao_reference(get_cartesian_shell(), magnetic_index(i));
        } else {
            const auto [x, y, z] = cartesian_powers(i);
            return const_ao_reference(get_contracted_gaussian(), x, y, z);
        }
    }

    /// Throws std::out_of_range if @p i is not a valid offset into *this
    void check_offset_(size_type i) const {
        if(i < size()) return;
        throw std::out_of_range("chemist::experimental::CCAShell: offset " +
                                std::to_string(i) +
                                " is out of range for a shell with " +
                                std::to_string(size()) + " AOs.");
    }

    /// Wraps casting *this to the derived class
    DerivedType& downcast_() noexcept {
        return static_cast<DerivedType&>(*this);
    }

    /// Wraps casting *this to a read-only reference to the derived class
    const DerivedType& downcast_() const noexcept {
        return static_cast<const DerivedType&>(*this);
    }
};

} // namespace chemist::experimental
