/*
 * This file is autogenerated by generate_basis.py.  Any modifications made in
 * this file will be lost next time generate_basis.py is run.
 */

#include "libchemist/defaults/nwx_basis_list.hpp"

namespace libchemist::detail_ {

Center<double> three_dash_21g_star(std::size_t Z) {
    switch(Z) {
        case(11): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0674911, 0.3935050, 0.6656050},
              std::vector<double>{547.6130000, 82.0678000, 17.6917000});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.1119370, 0.2546540, 0.8444170},
                         std::vector<double>{17.5407000, 3.7939800, 0.9064410});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.1282330, 0.4715330, 0.6042730},
                         std::vector<double>{17.5407000, 3.7939800, 0.9064410});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.2196600, 1.0891200},
                         std::vector<double>{0.5018240, 0.0609458});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.0090665, 0.9972020},
                         std::vector<double>{0.5018240, 0.0609458});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0244349});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0244349});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.1750000});
            return rv;
        } // End case
        case(12): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0675982, 0.3917780, 0.6666610},
              std::vector<double>{652.8410000, 98.3805000, 21.2996000});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.1102460, 0.1841190, 0.8963990},
                         std::vector<double>{23.3727000, 5.1995300, 1.3150800});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.1210140, 0.4628100, 0.6069070},
                         std::vector<double>{23.3727000, 5.1995300, 1.3150800});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.3611010, 1.2150500},
                         std::vector<double>{0.6113490, 0.1418410});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.0242633, 0.9866730},
                         std::vector<double>{0.6113490, 0.1418410});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0464011});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0464011});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.1750000});
            return rv;
        } // End case
        case(13): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0668347, 0.3890610, 0.6694680},
              std::vector<double>{775.7370000, 116.9520000, 25.3326000});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.1079020, 0.1462450, 0.9237300},
                         std::vector<double>{29.4796000, 6.6331400, 1.7267500});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.1175740, 0.4611740, 0.6055350},
                         std::vector<double>{29.4796000, 6.6331400, 1.7267500});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.3203270, 1.1841200},
                         std::vector<double>{0.9461600, 0.2025060});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.0519383, 0.9726600},
                         std::vector<double>{0.9461600, 0.2025060});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0639088});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0639088});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.3250000});
            return rv;
        } // End case
        case(14): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0660823, 0.3862290, 0.6723800},
              std::vector<double>{910.6550000, 137.3360000, 29.7601000});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.1045110, 0.1074100, 0.9514460},
                         std::vector<double>{36.6716000, 8.3172900, 2.2164500});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.1133550, 0.4575780, 0.6074270},
                         std::vector<double>{36.6716000, 8.3172900, 2.2164500});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.3761080, 1.2516500},
                         std::vector<double>{1.0791300, 0.3024220});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.0671030, 0.9568830},
                         std::vector<double>{1.0791300, 0.3024220});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0933392});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0933392});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.4500000});
            return rv;
        } // End case
        case(15): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0655410, 0.3840360, 0.6745410},
              std::vector<double>{1054.9000000, 159.1950000, 34.5304000});
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{-0.1021300, 0.0815920, 0.9697880},
              std::vector<double>{44.2866000, 10.1019000, 2.7399700});
            rv.add_shell(
              ShellType::pure, 1,
              std::vector<double>{0.1108510, 0.4564950, 0.6069360},
              std::vector<double>{44.2866000, 10.1019000, 2.7399700});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.3714950, 1.2709900},
                         std::vector<double>{1.2186500, 0.3955460});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.0915820, 0.9349240},
                         std::vector<double>{1.2186500, 0.3955460});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.1228110});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.1228110});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.5500000});
            return rv;
        } // End case
        case(16): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0650070, 0.3820400, 0.6765450},
              std::vector<double>{1210.6200000, 182.7470000, 39.6673000});
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{-0.1003100, 0.0650880, 0.9814550},
              std::vector<double>{52.2236000, 11.9629000, 3.2891100});
            rv.add_shell(
              ShellType::pure, 1,
              std::vector<double>{0.1096460, 0.4576490, 0.6042610},
              std::vector<double>{52.2236000, 11.9629000, 3.2891100});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.2860890, 1.2280600},
                         std::vector<double>{1.2238400, 0.4573030});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.1647770, 0.8708550},
                         std::vector<double>{1.2238400, 0.4573030});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.1422690});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.1422690});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.6500000});
            return rv;
        } // End case
        case(17): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0645827, 0.3803630, 0.6781900},
              std::vector<double>{1376.4000000, 207.8570000, 45.1554000});
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{-0.0987639, 0.0511338, 0.9913370},
              std::vector<double>{60.8014000, 13.9765000, 3.8871000});
            rv.add_shell(
              ShellType::pure, 1,
              std::vector<double>{0.1085980, 0.4586820, 0.6019620},
              std::vector<double>{60.8014000, 13.9765000, 3.8871000});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.2224010, 1.1825200},
                         std::vector<double>{1.3529900, 0.5269550});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.2192160, 0.8223210},
                         std::vector<double>{1.3529900, 0.5269550});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.1667140});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.1667140});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.7500000});
            return rv;
        } // End case
        case(18): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0641707, 0.3787970, 0.6797520},
              std::vector<double>{1553.7100000, 234.6780000, 51.0121000});
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{-0.0974661, 0.0390569, 0.9999160},
              std::vector<double>{70.0453000, 16.1473000, 4.5349200});
            rv.add_shell(
              ShellType::pure, 1,
              std::vector<double>{0.1076190, 0.4595760, 0.6000410},
              std::vector<double>{70.0453000, 16.1473000, 4.5349200});
            rv.add_shell(ShellType::pure, 0,
                         std::vector<double>{-0.1768660, 1.1469000},
                         std::vector<double>{1.5420900, 0.6072670});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.2556870, 0.7898420},
                         std::vector<double>{1.5420900, 0.6072670});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.1953730});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.1953730});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.8500000});
            return rv;
        } // End case
        default: { throw std::out_of_range("Basis not available for Z"); }
    } // end switch

} // end function
} // namespace libchemist::detail_