set(LIBCHEMIST_BASIS_SOURCE
    defaults/bases/3-21++g.cpp
    defaults/bases/3-21++g_star.cpp
    defaults/bases/3-21g.cpp
    defaults/bases/3-21g_star.cpp
    defaults/bases/3-21g_star_polarization.cpp
    defaults/bases/3-21gsp.cpp
    defaults/bases/6-31++g.cpp
    defaults/bases/6-31++g_star.cpp
    defaults/bases/6-31++g_star_star.cpp
    defaults/bases/6-31++g_star_star-j.cpp
    defaults/bases/6-31+g.cpp
    defaults/bases/6-31+g_star.cpp
    defaults/bases/6-31+g_star-j.cpp
    defaults/bases/6-31+g_star_star.cpp
    defaults/bases/6-311++g.cpp
    defaults/bases/6-311++g_star.cpp
    defaults/bases/6-311++g_star_star.cpp
    defaults/bases/6-311++g_star_star-j.cpp
    defaults/bases/6-311+g.cpp
    defaults/bases/6-311+g_star.cpp
    defaults/bases/6-311+g_star-j.cpp
    defaults/bases/6-311+g_star_star.cpp
    defaults/bases/6-311g.cpp
    defaults/bases/6-311g-j.cpp
    defaults/bases/6-311g_star.cpp
    defaults/bases/6-311g_star_polarization.cpp
    defaults/bases/6-311g_star_star.cpp
    defaults/bases/6-311g_star_star_polarization.cpp
    defaults/bases/6-31g.cpp
    defaults/bases/6-31g-blaudeau.cpp
    defaults/bases/6-31g-j.cpp
    defaults/bases/6-31g_star.cpp
    defaults/bases/6-31g_star-blaudeau.cpp
    defaults/bases/6-31g_star_polarization.cpp
    defaults/bases/6-31g_star_star.cpp
    defaults/bases/6-31g_star_star_polarization.cpp
    defaults/bases/aug-cc-pcv5z.cpp
    defaults/bases/aug-cc-pcvdz.cpp
    defaults/bases/aug-cc-pcvdz-dk.cpp
    defaults/bases/aug-cc-pcvqz.cpp
    defaults/bases/aug-cc-pcvqz-dk.cpp
    defaults/bases/aug-cc-pcvtz.cpp
    defaults/bases/aug-cc-pcvtz-dk.cpp
    defaults/bases/aug-cc-pv5z.cpp
    defaults/bases/aug-cc-pv5z-dk.cpp
    defaults/bases/aug-cc-pv5z-dk_diffuse.cpp
    defaults/bases/aug-cc-pv5z-nr.cpp
    defaults/bases/aug-cc-pv5z-nr_diffuse.cpp
    defaults/bases/aug-cc-pv5z-nr_mp2_fitting.cpp
    defaults/bases/aug-cc-pv5z-pp-ri_diffuse.cpp
    defaults/bases/aug-cc-pv5z-pp_mp2_fitting.cpp
    defaults/bases/aug-cc-pv5z-pp_optri.cpp
    defaults/bases/aug-cc-pv5z-ri_diffuse.cpp
    defaults/bases/aug-cc-pv5z_diffuse.cpp
    defaults/bases/aug-cc-pv5z_optri.cpp
    defaults/bases/aug-cc-pv6z.cpp
    defaults/bases/aug-cc-pv6z-ri_diffuse.cpp
    defaults/bases/aug-cc-pv6z_diffuse.cpp
    defaults/bases/aug-cc-pv7z.cpp
    defaults/bases/aug-cc-pvdz.cpp
    defaults/bases/aug-cc-pvdz-dk.cpp
    defaults/bases/aug-cc-pvdz-dk_diffuse.cpp
    defaults/bases/aug-cc-pvdz-pp-ri_diffuse.cpp
    defaults/bases/aug-cc-pvdz-pp_diffuse.cpp
    defaults/bases/aug-cc-pvdz-pp_mp2_fitting.cpp
    defaults/bases/aug-cc-pvdz-pp_optri.cpp
    defaults/bases/aug-cc-pvdz-ri_diffuse.cpp
    defaults/bases/aug-cc-pvdz_diffuse.cpp
    defaults/bases/aug-cc-pvdz_optri.cpp
    defaults/bases/aug-cc-pvqz.cpp
    defaults/bases/aug-cc-pvqz-dk.cpp
    defaults/bases/aug-cc-pvqz-dk_diffuse.cpp
    defaults/bases/aug-cc-pvqz-nr.cpp
    defaults/bases/aug-cc-pvqz-nr_diffuse.cpp
    defaults/bases/aug-cc-pvqz-nr_mp2_fitting.cpp
    defaults/bases/aug-cc-pvqz-pp-ri_diffuse.cpp
    defaults/bases/aug-cc-pvqz-pp_mp2_fitting.cpp
    defaults/bases/aug-cc-pvqz-pp_optri.cpp
    defaults/bases/aug-cc-pvqz-ri_diffuse.cpp
    defaults/bases/aug-cc-pvqz_diffuse.cpp
    defaults/bases/aug-cc-pvqz_optri.cpp
    defaults/bases/aug-cc-pvtz.cpp
    defaults/bases/aug-cc-pvtz-dk.cpp
    defaults/bases/aug-cc-pvtz-dk_diffuse.cpp
    defaults/bases/aug-cc-pvtz-j.cpp
    defaults/bases/aug-cc-pvtz-nr.cpp
    defaults/bases/aug-cc-pvtz-nr_diffuse.cpp
    defaults/bases/aug-cc-pvtz-nr_mp2_fitting.cpp
    defaults/bases/aug-cc-pvtz-pp-ri_diffuse.cpp
    defaults/bases/aug-cc-pvtz-pp_mp2_fitting.cpp
    defaults/bases/aug-cc-pvtz-pp_optri.cpp
    defaults/bases/aug-cc-pvtz-ri_diffuse.cpp
    defaults/bases/aug-cc-pvtz_diffuse.cpp
    defaults/bases/aug-cc-pvtz_mp2_fitting.cpp
    defaults/bases/aug-cc-pvtz_optri.cpp
    defaults/bases/aug-cc-pwcv5z.cpp
    defaults/bases/aug-cc-pwcv5z-dk.cpp
    defaults/bases/aug-cc-pwcv5z-nr.cpp
    defaults/bases/aug-cc-pwcv5z-pp_mp2_fitting.cpp
    defaults/bases/aug-cc-pwcv5z-pp_optri.cpp
    defaults/bases/aug-cc-pwcvdz.cpp
    defaults/bases/aug-cc-pwcvdz-pp_mp2_fitting.cpp
    defaults/bases/aug-cc-pwcvdz-pp_optri.cpp
    defaults/bases/aug-cc-pwcvqz.cpp
    defaults/bases/aug-cc-pwcvqz-dk.cpp
    defaults/bases/aug-cc-pwcvqz-nr.cpp
    defaults/bases/aug-cc-pwcvqz-pp_mp2_fitting.cpp
    defaults/bases/aug-cc-pwcvqz-pp_optri.cpp
    defaults/bases/aug-cc-pwcvtz.cpp
    defaults/bases/aug-cc-pwcvtz-dk.cpp
    defaults/bases/aug-cc-pwcvtz-nr.cpp
    defaults/bases/aug-cc-pwcvtz-nr_mp2_fitting.cpp
    defaults/bases/aug-cc-pwcvtz-pp_mp2_fitting.cpp
    defaults/bases/aug-cc-pwcvtz-pp_optri.cpp
    defaults/bases/cc-pcv5z.cpp
    defaults/bases/cc-pcv5z0.cpp
    defaults/bases/cc-pcv6z.cpp
    defaults/bases/cc-pcvdz.cpp
    defaults/bases/cc-pcvdz-f12.cpp
    defaults/bases/cc-pcvdz-f12_mp2_fitting.cpp
    defaults/bases/cc-pcvdz-f12_optri.cpp
    defaults/bases/cc-pcvqz.cpp
    defaults/bases/cc-pcvqz-f12.cpp
    defaults/bases/cc-pcvqz-f12_mp2_fitting.cpp
    defaults/bases/cc-pcvqz-f12_optri.cpp
    defaults/bases/cc-pcvtz.cpp
    defaults/bases/cc-pcvtz-f12.cpp
    defaults/bases/cc-pcvtz-f12_mp2_fitting.cpp
    defaults/bases/cc-pcvtz-f12_optri.cpp
    defaults/bases/cc-pv5z.cpp
    defaults/bases/cc-pv5z-dk.cpp
    defaults/bases/cc-pv5z-nr.cpp
    defaults/bases/cc-pv5z-nr_mp2_fitting.cpp
    defaults/bases/cc-pv5z-pp-ri.cpp
    defaults/bases/cc-pv5z-pp_mp2_fitting.cpp
    defaults/bases/cc-pv5z-ri.cpp
    defaults/bases/cc-pv6z.cpp
    defaults/bases/cc-pv6z-ri.cpp
    defaults/bases/cc-pv8z.cpp
    defaults/bases/cc-pv9z.cpp
    defaults/bases/cc-pvdz.cpp
    defaults/bases/cc-pvdz-dk.cpp
    defaults/bases/cc-pvdz-dk3.cpp
    defaults/bases/cc-pvdz-f12.cpp
    defaults/bases/cc-pvdz-f12_mp2_fitting.cpp
    defaults/bases/cc-pvdz-f12_optri.cpp
    defaults/bases/cc-pvdz-fit2-1.cpp
    defaults/bases/cc-pvdz-jkfit.cpp
    defaults/bases/cc-pvdz-pp-ri.cpp
    defaults/bases/cc-pvdz-pp_mp2_fitting.cpp
    defaults/bases/cc-pvdz-ri.cpp
    defaults/bases/cc-pvqz.cpp
    defaults/bases/cc-pvqz-dk.cpp
    defaults/bases/cc-pvqz-dk3.cpp
    defaults/bases/cc-pvqz-f12.cpp
    defaults/bases/cc-pvqz-f12_mp2_fitting.cpp
    defaults/bases/cc-pvqz-f12_optri.cpp
    defaults/bases/cc-pvqz-nr.cpp
    defaults/bases/cc-pvqz-nr_mp2_fitting.cpp
    defaults/bases/cc-pvqz-pp-ri.cpp
    defaults/bases/cc-pvqz-pp_mp2_fitting.cpp
    defaults/bases/cc-pvqz-ri.cpp
    defaults/bases/cc-pvtz.cpp
    defaults/bases/cc-pvtz+.cpp
    defaults/bases/cc-pvtz-dk.cpp
    defaults/bases/cc-pvtz-dk3.cpp
    defaults/bases/cc-pvtz-f12.cpp
    defaults/bases/cc-pvtz-f12_mp2_fitting.cpp
    defaults/bases/cc-pvtz-f12_optri.cpp
    defaults/bases/cc-pvtz-fit2-1.cpp
    defaults/bases/cc-pvtz-nr.cpp
    defaults/bases/cc-pvtz-pp-ri.cpp
    defaults/bases/cc-pvtz-pp_mp2_fitting.cpp
    defaults/bases/cc-pvtz-ri.cpp
    defaults/bases/cc-pvtz_mp2_fitting.cpp
    defaults/bases/cc-pwcv5z.cpp
    defaults/bases/cc-pwcv5z-dk.cpp
    defaults/bases/cc-pwcv5z-nr.cpp
    defaults/bases/cc-pwcv5z-pp_mp2_fitting.cpp
    defaults/bases/cc-pwcv5z-ri.cpp
    defaults/bases/cc-pwcv5z-ri_tight.cpp
    defaults/bases/cc-pwcv5z_core_set.cpp
    defaults/bases/cc-pwcv5z_tight.cpp
    defaults/bases/cc-pwcvdz.cpp
    defaults/bases/cc-pwcvdz-dk3.cpp
    defaults/bases/cc-pwcvdz-pp_mp2_fitting.cpp
    defaults/bases/cc-pwcvdz-ri.cpp
    defaults/bases/cc-pwcvdz-ri_tight.cpp
    defaults/bases/cc-pwcvdz_tight.cpp
    defaults/bases/cc-pwcvqz.cpp
    defaults/bases/cc-pwcvqz-dk.cpp
    defaults/bases/cc-pwcvqz-dk3.cpp
    defaults/bases/cc-pwcvqz-nr.cpp
    defaults/bases/cc-pwcvqz-pp_mp2_fitting.cpp
    defaults/bases/cc-pwcvqz-ri.cpp
    defaults/bases/cc-pwcvqz-ri_tight.cpp
    defaults/bases/cc-pwcvqz_tight.cpp
    defaults/bases/cc-pwcvtz.cpp
    defaults/bases/cc-pwcvtz-dk.cpp
    defaults/bases/cc-pwcvtz-dk3.cpp
    defaults/bases/cc-pwcvtz-nr.cpp
    defaults/bases/cc-pwcvtz-nr_mp2_fitting.cpp
    defaults/bases/cc-pwcvtz-pp_mp2_fitting.cpp
    defaults/bases/cc-pwcvtz-ri.cpp
    defaults/bases/cc-pwcvtz-ri_tight.cpp
    defaults/bases/cc-pwcvtz_tight.cpp
    defaults/bases/sto-3g.cpp
)
