/*
 * This file is autogenerated by generate_basis.py.  Any modifications made in
 * this file will be lost next time generate_basis.py is run.
 */

#include "libchemist/defaults/nwx_basis_list.hpp"

namespace libchemist::detail_ {

AOBasisSet aug_dash_cc_dash_pvqz_dash_pp_dash_ri_diffuse(std::size_t Z) {
    switch(Z) {
        case(29): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.30702700000e-01, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.40005500000e-01, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.70093300000e-01, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.12420800000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.19048000000, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.58142000000, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{1.2456000000, 1.0000000},
              },
              AOShell{
                8,
                AOPrimitive{2.4332500000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(30): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.36340900000e-01, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.46946100000e-01, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.87608000000e-01, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.14886000000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.20299700000, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.75396900000, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{1.5323600000, 1.0000000},
              },
              AOShell{
                8,
                AOPrimitive{2.9459900000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(47): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.15767000000e-01, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.19923100000e-01, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.36648200000e-01, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.62398400000e-01, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.99162600000e-01, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.40085900000, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{0.71419500000, 1.0000000},
              },
              AOShell{
                8,
                AOPrimitive{1.2746300000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(48): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.18612800000e-01, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.23647800000e-01, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.43784800000e-01, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.75382700000e-01, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.12279200000, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.50263600000, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{0.87751000000, 1.0000000},
              },
              AOShell{
                8,
                AOPrimitive{1.5083900000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(79): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.15820800000e-01, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.19893700000e-01, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.36767200000e-01, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.68079500000e-01, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.11497500000, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.33547700000, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{0.58223200000, 1.0000000},
              },
              AOShell{
                8,
                AOPrimitive{0.94443300000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(80): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.19260000000e-01, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.23454600000e-01, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.43347600000e-01, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.10552600000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.16582200000, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.42038900000, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{0.66630100000, 1.0000000},
              },
              AOShell{
                8,
                AOPrimitive{1.0675500000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        default: { throw std::out_of_range("Basis not available for Z"); }
    } // end switch

} // end function
} // namespace libchemist::detail_
