/*
 * This file is autogenerated by generate_basis.py.  Any modifications made in
 * this file will be lost next time generate_basis.py is run.
 */

#include "libchemist/defaults/nwx_basis_list.hpp"

namespace libchemist::detail_ {

AOBasisSet aug_dash_cc_dash_pvqz_dash_nr_diffuse(std::size_t Z) {
    switch(Z) {
        case(21): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0104700, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0101200, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0095200, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.0312800, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.0723600, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.1226400, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(22): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0111000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0110300, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0127900, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.0554100, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.1256600, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.2724200, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(23): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0117200, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0116600, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0163000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.0818500, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.1933900, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.4711900, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(24): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0115700, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0123300, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0177800, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1037300, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.2454500, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.6329200, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(25): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0128000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0128700, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0197800, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1282900, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.3184100, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.7767100, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(26): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0134800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0130500, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0220500, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1551400, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.4073800, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.9587800, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(27): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0140900, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0142100, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0243200, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1841600, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.4963100, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.1579100, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(28): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0146700, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0138800, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0269100, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.2265000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.6237000, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.4486000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(29): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0152400, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0142600, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0461400, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.2574700, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.7321200, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.6768100, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(30): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{0.0157600, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0147200, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0659800, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.2994900, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.8673600, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{2.0273400, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        default: { throw std::out_of_range("Basis not available for Z"); }
    } // end switch

} // end function
} // namespace libchemist::detail_
