/*
 * This file is autogenerated by generate_basis.py.  Any modifications made in
 * this file will be lost next time generate_basis.py is run.
 */

#include "libchemist/defaults/nwx_basis_list.hpp"

namespace libchemist::detail_ {

AOBasisSet aug_dash_cc_dash_pvtz_dash_pp_optri(std::size_t Z) {
    switch(Z) {
        case(29): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{15.7721900, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{10.5744700, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{4.1727000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{2.6091000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.7545010, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.9524060, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.3594860, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{24.6157200, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{8.4652000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{4.8475730, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{2.1782000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.4537210, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.2864400, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{19.2536200, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{10.6972500, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{5.9415000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{3.3806000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.1746550, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.4592230, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{40.5299000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{12.2237300, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{2.8804730, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{1.9227800, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.6804820, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{19.5433400, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{8.6183000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{5.2316340, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{2.1983820, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.6200380, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{15.8827700, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{6.7627560, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{2.8311860, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.1309880, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{5.4682390, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(30): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{18.0156600, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{12.0880700, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{4.5786000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{2.8641000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.9284740, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.0441780, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.4211660, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{56.6060600, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{14.6815800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{9.2192000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{5.2228110, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{2.3491000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.1160830, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{23.7157300, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{11.3172500, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{6.6860000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{4.0411000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{2.6941890, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.6540230, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{35.2811000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{13.1821700, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{8.7979740, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{2.9859060, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.8090970, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{23.8968200, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{9.7523000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{6.4981750, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{2.5669490, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.7415720, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{20.7236100, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{8.2648140, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{3.6335050, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.4885070, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{6.4232100, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(47): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{12.9880100, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{8.6662790, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{5.7638620, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{2.2252000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.3969000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.9330580, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.4387890, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{13.3073000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{8.9584390, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{3.5359000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.2402000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.8365060, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.3466010, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{56.0864700, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{12.6350100, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{8.3996330, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{4.4524000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.5748000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.6887130, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{18.4005100, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{5.8492330, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{3.8949010, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{1.3934570, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.4319710, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{18.1892300, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{12.1284200, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{3.4990000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{1.0602030, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.4485200, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{6.5612130, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{3.7654840, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.8351940, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.7682030, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{2.2677190, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(48): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{14.0033000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{9.3781600, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{6.2810640, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{2.3847000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.4979000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.9230580, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.4476570, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{14.1936900, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{9.6352000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{3.8946000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.3110000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.8908050, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.3519550, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{53.1135200, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{14.6220100, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{8.5679360, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{5.0344000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.8041000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.7707920, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{12.5015000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{4.7847500, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{1.9146020, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{1.2761520, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.5075280, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{9.0379910, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{6.0128280, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{3.8914000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{1.2249850, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.4278500, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{7.3591130, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{3.8335400, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.8353910, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.7685240, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{2.5584550, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(79): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{15.8646600, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{10.5863500, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{7.0672090, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{2.9724350, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.9834000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.2448000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.8319210, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{11.7883500, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{8.0161500, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{2.6637000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.1410000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.7680020, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1822350, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{11.5463000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{7.7001940, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{3.4696000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.2171000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.5904350, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2063210, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{5.7087640, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{3.8055220, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{2.5389910, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.8029970, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.3058530, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{6.0586110, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{4.0649930, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{2.7283000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.8213260, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.3668080, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{5.1133800, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{3.4081930, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.6497500, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.7040980, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{1.7233740, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(80): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{20.3403200, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{13.5899500, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{9.0798070, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{3.1756500, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{2.1304000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.3378000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.5272570, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{11.8058700, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{8.0785100, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{2.8228000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.1949000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.8019890, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1913850, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{11.8098900, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{7.8919990, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{3.7153000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.3573000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.6721510, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.4037470, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{7.2773820, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{4.8571940, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{3.2423690, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.8100520, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.3271110, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{9.9730510, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{6.6487690, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{4.4367660, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{2.9668000, 1.0000000},
              },
              AOShell{
                4,
                AOPrimitive{0.4200240, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{7.1550830, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{4.2724950, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{1.9604390, 1.0000000},
              },
              AOShell{
                5,
                AOPrimitive{0.8778760, 1.0000000},
              },
              AOShell{
                6,
                AOPrimitive{1.8817780, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        default: { throw std::out_of_range("Basis not available for Z"); }
    } // end switch

} // end function
} // namespace libchemist::detail_
