/*
 * This file is autogenerated by generate_basis.py.  Any modifications made in
 * this file will be lost next time generate_basis.py is run.
 */

#include "libchemist/defaults/nwx_basis_list.hpp"

namespace libchemist::detail_ {

Center<double> aug_dash_cc_dash_pvtz_dash_pp_optri(std::size_t Z) {
    switch(Z) {
        case(29): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{15.7721900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{10.5744700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{4.1727000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{2.6091000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.7545010});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.9524060});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.3594860});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{24.6157200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{8.4652000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{4.8475730});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{2.1782000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{1.4537210});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.2864400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{19.2536200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{10.6972500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{5.9415000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{3.3806000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{1.1746550});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.4592230});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{40.5299000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{12.2237300});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{2.8804730});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{1.9227800});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.6804820});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{19.5433400});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{8.6183000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{5.2316340});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{2.1983820});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.6200380});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{15.8827700});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{6.7627560});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{2.8311860});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.1309880});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{5.4682390});
            return rv;
        } // End case
        case(30): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{18.0156600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{12.0880700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{4.5786000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{2.8641000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.9284740});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.0441780});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.4211660});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{56.6060600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{14.6815800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{9.2192000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{5.2228110});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{2.3491000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{1.1160830});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{23.7157300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{11.3172500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{6.6860000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{4.0411000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{2.6941890});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.6540230});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{35.2811000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{13.1821700});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{8.7979740});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{2.9859060});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.8090970});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{23.8968200});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{9.7523000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{6.4981750});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{2.5669490});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.7415720});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{20.7236100});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{8.2648140});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{3.6335050});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.4885070});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{6.4232100});
            return rv;
        } // End case
        case(47): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{12.9880100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{8.6662790});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{5.7638620});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{2.2252000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.3969000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.9330580});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.4387890});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{13.3073000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{8.9584390});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{3.5359000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{1.2402000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.8365060});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.3466010});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{56.0864700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{12.6350100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{8.3996330});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{4.4524000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{1.5748000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.6887130});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{18.4005100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{5.8492330});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{3.8949010});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{1.3934570});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.4319710});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{18.1892300});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{12.1284200});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{3.4990000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{1.0602030});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.4485200});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{6.5612130});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{3.7654840});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.8351940});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.7682030});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{2.2677190});
            return rv;
        } // End case
        case(48): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{14.0033000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{9.3781600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{6.2810640});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{2.3847000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.4979000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.9230580});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.4476570});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{14.1936900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{9.6352000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{3.8946000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{1.3110000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.8908050});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.3519550});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{53.1135200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{14.6220100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{8.5679360});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{5.0344000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{1.8041000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.7707920});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{12.5015000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{4.7847500});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{1.9146020});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{1.2761520});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.5075280});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{9.0379910});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{6.0128280});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{3.8914000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{1.2249850});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.4278500});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{7.3591130});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{3.8335400});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.8353910});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.7685240});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{2.5584550});
            return rv;
        } // End case
        case(79): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{15.8646600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{10.5863500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{7.0672090});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{2.9724350});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.9834000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.2448000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.8319210});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{11.7883500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{8.0161500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{2.6637000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{1.1410000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.7680020});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.1822350});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{11.5463000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{7.7001940});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{3.4696000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{1.2171000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.5904350});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.2063210});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{5.7087640});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{3.8055220});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{2.5389910});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.8029970});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.3058530});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{6.0586110});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{4.0649930});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{2.7283000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.8213260});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.3668080});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{5.1133800});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{3.4081930});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.6497500});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.7040980});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{1.7233740});
            return rv;
        } // End case
        case(80): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{20.3403200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{13.5899500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{9.0798070});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{3.1756500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{2.1304000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.3378000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.5272570});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{11.8058700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{8.0785100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{2.8228000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{1.1949000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.8019890});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.1913850});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{11.8098900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{7.8919990});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{3.7153000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{1.3573000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.6721510});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.4037470});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{7.2773820});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{4.8571940});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{3.2423690});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.8100520});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.3271110});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{9.9730510});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{6.6487690});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{4.4367660});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{2.9668000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.4200240});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{7.1550830});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{4.2724950});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.9604390});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.8778760});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{1.8817780});
            return rv;
        } // End case
        default: { throw std::out_of_range("Basis not available for Z"); }
    } // end switch

} // end function
} // namespace libchemist::detail_