/*
 * This file is autogenerated by generate_basis.py.  Any modifications made in
 * this file will be lost next time generate_basis.py is run.
 */

#include "libchemist/defaults/nwx_basis_list.hpp"

namespace libchemist::detail_ {

AOBasisSet cc_dash_pcvtz_dash_f12(std::size_t Z) {
    switch(Z) {
        case(3): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{6601.0000000, 0.0001170},
                AOPrimitive{989.7000000, 0.0009110},
                AOPrimitive{225.7000000, 0.0047280},
                AOPrimitive{64.2900000, 0.0191970},
                AOPrimitive{21.1800000, 0.0630470},
                AOPrimitive{7.7240000, 0.1632080},
                AOPrimitive{3.0030000, 0.3148270},
                AOPrimitive{1.2120000, 0.3939360},
                AOPrimitive{0.4930000, 0.1969180},
              },
              AOShell{
                0,
                AOPrimitive{6601.0000000, -0.0000180},
                AOPrimitive{989.7000000, -0.0001420},
                AOPrimitive{225.7000000, -0.0007410},
                AOPrimitive{64.2900000, -0.0030200},
                AOPrimitive{21.1800000, -0.0101230},
                AOPrimitive{7.7240000, -0.0270940},
                AOPrimitive{3.0030000, -0.0573590},
                AOPrimitive{1.2120000, -0.0938950},
                AOPrimitive{0.4930000, -0.1210910},
              },
              AOShell{
                0,
                AOPrimitive{0.0951500, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0479100, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0222000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0064000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.4061290, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{6.2500000, 0.0033880},
                AOPrimitive{1.3700000, 0.0193160},
              },
              AOShell{
                1,
                AOPrimitive{0.3672000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1192000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0447400, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0179500, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0075000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.3752600, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2351180, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.1194040, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0606390, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{4.5186740, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1637750, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.0759100, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(4): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{14630.0000000, 0.0000920},
                AOPrimitive{2191.0000000, 0.0007130},
                AOPrimitive{498.2000000, 0.0037350},
                AOPrimitive{140.9000000, 0.0154680},
                AOPrimitive{45.8600000, 0.0528740},
                AOPrimitive{16.4700000, 0.1456940},
                AOPrimitive{6.3190000, 0.3026810},
                AOPrimitive{2.5350000, 0.4049360},
                AOPrimitive{1.0350000, 0.2223870},
              },
              AOShell{
                0,
                AOPrimitive{14630.0000000, -0.0000170},
                AOPrimitive{2191.0000000, -0.0001300},
                AOPrimitive{498.2000000, -0.0006790},
                AOPrimitive{140.9000000, -0.0028570},
                AOPrimitive{45.8600000, -0.0098130},
                AOPrimitive{16.4700000, -0.0286090},
                AOPrimitive{6.3190000, -0.0637600},
                AOPrimitive{2.5350000, -0.1172310},
                AOPrimitive{1.0350000, -0.1212020},
              },
              AOShell{
                0,
                AOPrimitive{0.2528000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1052000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0426100, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0141000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.1657720, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{14.0300000, 0.0040990},
                AOPrimitive{3.1680000, 0.0256260},
              },
              AOShell{
                1,
                AOPrimitive{0.9024000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.3036000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1130000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0428600, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0084000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{3.1025030, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.4670460, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2205970, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.1041940, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{5.9915790, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.3166400, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1457880, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(5): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{23870.0000000, 0.0000880},
                AOPrimitive{3575.0000000, 0.0006870},
                AOPrimitive{812.8000000, 0.0036000},
                AOPrimitive{229.7000000, 0.0149490},
                AOPrimitive{74.6900000, 0.0514350},
                AOPrimitive{26.8100000, 0.1433020},
                AOPrimitive{10.3200000, 0.3009350},
                AOPrimitive{4.1780000, 0.4035260},
                AOPrimitive{1.7270000, 0.2253400},
              },
              AOShell{
                0,
                AOPrimitive{23870.0000000, -0.0000180},
                AOPrimitive{3575.0000000, -0.0001390},
                AOPrimitive{812.8000000, -0.0007250},
                AOPrimitive{229.7000000, -0.0030630},
                AOPrimitive{74.6900000, -0.0105810},
                AOPrimitive{26.8100000, -0.0313650},
                AOPrimitive{10.3200000, -0.0710120},
                AOPrimitive{4.1780000, -0.1321030},
                AOPrimitive{1.7270000, -0.1230720},
              },
              AOShell{
                0,
                AOPrimitive{0.4704000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1896000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0739400, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0272100, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{1.9893800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{22.2600000, 0.0050950},
                AOPrimitive{5.0580000, 0.0332060},
              },
              AOShell{
                1,
                AOPrimitive{1.4870000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.5071000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1812000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0646300, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0187800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{4.8920970, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.4403000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.5333000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.1975000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{8.0734650, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.8479000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.2484000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(6): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{33980.0000000, 0.0000910},
                AOPrimitive{5089.0000000, 0.0007040},
                AOPrimitive{1157.0000000, 0.0036930},
                AOPrimitive{326.6000000, 0.0153600},
                AOPrimitive{106.1000000, 0.0529290},
                AOPrimitive{38.1100000, 0.1470430},
                AOPrimitive{14.7500000, 0.3056310},
                AOPrimitive{6.0350000, 0.3993450},
                AOPrimitive{2.5300000, 0.2170510},
              },
              AOShell{
                0,
                AOPrimitive{33980.0000000, -0.0000190},
                AOPrimitive{5089.0000000, -0.0001510},
                AOPrimitive{1157.0000000, -0.0007850},
                AOPrimitive{326.6000000, -0.0033240},
                AOPrimitive{106.1000000, -0.0115120},
                AOPrimitive{38.1100000, -0.0341600},
                AOPrimitive{14.7500000, -0.0771730},
                AOPrimitive{6.0350000, -0.1414930},
                AOPrimitive{2.5300000, -0.1180190},
              },
              AOShell{
                0,
                AOPrimitive{0.7355000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.2905000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1111000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0414500, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{3.0284870, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{34.5100000, 0.0053780},
                AOPrimitive{7.9150000, 0.0361320},
              },
              AOShell{
                1,
                AOPrimitive{2.3680000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.8132000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.2890000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1007000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0321800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{7.6364210, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{2.2805000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.7834000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2691000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{11.0167360, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{1.0371000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.3459000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(7): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{45840.0000000, 0.0000920},
                AOPrimitive{6868.0000000, 0.0007170},
                AOPrimitive{1563.0000000, 0.0037490},
                AOPrimitive{442.4000000, 0.0155320},
                AOPrimitive{144.3000000, 0.0531460},
                AOPrimitive{52.1800000, 0.1467870},
                AOPrimitive{20.3400000, 0.3046630},
                AOPrimitive{8.3810000, 0.3976840},
                AOPrimitive{3.5290000, 0.2176410},
              },
              AOShell{
                0,
                AOPrimitive{45840.0000000, -0.0000200},
                AOPrimitive{6868.0000000, -0.0001590},
                AOPrimitive{1563.0000000, -0.0008240},
                AOPrimitive{442.4000000, -0.0034780},
                AOPrimitive{144.3000000, -0.0119660},
                AOPrimitive{52.1800000, -0.0353880},
                AOPrimitive{20.3400000, -0.0800770},
                AOPrimitive{8.3810000, -0.1467220},
                AOPrimitive{3.5290000, -0.1163600},
              },
              AOShell{
                0,
                AOPrimitive{1.0540000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.4118000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1552000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0546400, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{4.2801780, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{49.3300000, 0.0055330},
                AOPrimitive{11.3700000, 0.0379620},
              },
              AOShell{
                1,
                AOPrimitive{3.4350000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.1820000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.4173000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1428000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0440200, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{10.9917450, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{3.0521000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.0393000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.3539000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{13.7725290, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{1.3498000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.4638000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(8): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{61420.0000000, 0.0000900},
                AOPrimitive{9199.0000000, 0.0006980},
                AOPrimitive{2091.0000000, 0.0036640},
                AOPrimitive{590.9000000, 0.0152180},
                AOPrimitive{192.3000000, 0.0524230},
                AOPrimitive{69.3200000, 0.1459210},
                AOPrimitive{26.9700000, 0.3052580},
                AOPrimitive{11.1000000, 0.3985080},
                AOPrimitive{4.6820000, 0.2169800},
              },
              AOShell{
                0,
                AOPrimitive{61420.0000000, -0.0000200},
                AOPrimitive{9199.0000000, -0.0001590},
                AOPrimitive{2091.0000000, -0.0008290},
                AOPrimitive{590.9000000, -0.0035080},
                AOPrimitive{192.3000000, -0.0121560},
                AOPrimitive{69.3200000, -0.0362610},
                AOPrimitive{26.9700000, -0.0829920},
                AOPrimitive{11.1000000, -0.1520900},
                AOPrimitive{4.6820000, -0.1153310},
              },
              AOShell{
                0,
                AOPrimitive{1.4280000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.5547000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.2067000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0695900, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{5.6522400, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{63.4200000, 0.0060440},
                AOPrimitive{14.6600000, 0.0417990},
              },
              AOShell{
                1,
                AOPrimitive{4.4590000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.5310000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.5302000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1750000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0534800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{14.1326080, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{3.3422000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.1491000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.3951000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{16.2222240, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{1.4956000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.5379000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(9): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{74530.0000000, 0.0000950},
                AOPrimitive{11170.0000000, 0.0007380},
                AOPrimitive{2543.0000000, 0.0038580},
                AOPrimitive{721.0000000, 0.0159260},
                AOPrimitive{235.9000000, 0.0542890},
                AOPrimitive{85.6000000, 0.1495130},
                AOPrimitive{33.5500000, 0.3082520},
                AOPrimitive{13.9300000, 0.3948530},
                AOPrimitive{5.9150000, 0.2110310},
              },
              AOShell{
                0,
                AOPrimitive{74530.0000000, -0.0000220},
                AOPrimitive{11170.0000000, -0.0001720},
                AOPrimitive{2543.0000000, -0.0008910},
                AOPrimitive{721.0000000, -0.0037480},
                AOPrimitive{235.9000000, -0.0128620},
                AOPrimitive{85.6000000, -0.0380610},
                AOPrimitive{33.5500000, -0.0862390},
                AOPrimitive{13.9300000, -0.1558650},
                AOPrimitive{5.9150000, -0.1109140},
              },
              AOShell{
                0,
                AOPrimitive{1.8430000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.7124000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.2637000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0859400, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{7.5409400, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{80.3900000, 0.0063470},
                AOPrimitive{18.6300000, 0.0442040},
              },
              AOShell{
                1,
                AOPrimitive{5.6940000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1.9530000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.6702000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.2166000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0656800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{17.8406930, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{4.2272000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.3897000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.4569000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{20.2081460, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{2.5974000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.8514000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(10): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{99920.0000000, 0.0000860},
                AOPrimitive{14960.0000000, 0.0006690},
                AOPrimitive{3399.0000000, 0.0035180},
                AOPrimitive{958.9000000, 0.0146670},
                AOPrimitive{311.2000000, 0.0509620},
                AOPrimitive{111.7000000, 0.1437440},
                AOPrimitive{43.3200000, 0.3045620},
                AOPrimitive{17.8000000, 0.4001050},
                AOPrimitive{7.5030000, 0.2186440},
              },
              AOShell{
                0,
                AOPrimitive{99920.0000000, -0.0000200},
                AOPrimitive{14960.0000000, -0.0001580},
                AOPrimitive{3399.0000000, -0.0008240},
                AOPrimitive{958.9000000, -0.0035000},
                AOPrimitive{311.2000000, -0.0122330},
                AOPrimitive{111.7000000, -0.0370170},
                AOPrimitive{43.3200000, -0.0861130},
                AOPrimitive{17.8000000, -0.1583810},
                AOPrimitive{7.5030000, -0.1142880},
              },
              AOShell{
                0,
                AOPrimitive{2.3370000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.9001000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.3301000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1054000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{9.1265080, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{99.6800000, 0.0065660},
                AOPrimitive{23.1500000, 0.0459790},
              },
              AOShell{
                1,
                AOPrimitive{7.1080000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{2.4410000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.8339000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.2662000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0817800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{22.2659280, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{6.7295000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{2.0114000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.6012000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{28.3643340, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{4.1702000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.9443000, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(11): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{1224000.0000000, 0.0000048},
                AOPrimitive{183200.0000000, 0.0000372},
                AOPrimitive{41700.0000000, 0.0001958},
                AOPrimitive{11810.0000000, 0.0008267},
                AOPrimitive{3853.0000000, 0.0030025},
                AOPrimitive{1391.0000000, 0.0097031},
                AOPrimitive{542.5000000, 0.0282337},
                AOPrimitive{224.9000000, 0.0732058},
                AOPrimitive{97.9300000, 0.1628970},
                AOPrimitive{44.3100000, 0.2887080},
                AOPrimitive{20.6500000, 0.3468290},
                AOPrimitive{9.7290000, 0.2068650},
                AOPrimitive{4.2280000, 0.0328009},
                AOPrimitive{1.9690000, -0.0006477},
                AOPrimitive{0.8890000, 0.0014588},
                AOPrimitive{0.3964000, -0.0001783},
              },
              AOShell{
                0,
                AOPrimitive{1224000.0000000, -0.0000012},
                AOPrimitive{183200.0000000, -0.0000091},
                AOPrimitive{41700.0000000, -0.0000478},
                AOPrimitive{11810.0000000, -0.0002020},
                AOPrimitive{3853.0000000, -0.0007358},
                AOPrimitive{1391.0000000, -0.0023875},
                AOPrimitive{542.5000000, -0.0070497},
                AOPrimitive{224.9000000, -0.0187856},
                AOPrimitive{97.9300000, -0.0446153},
                AOPrimitive{44.3100000, -0.0897741},
                AOPrimitive{20.6500000, -0.1429400},
                AOPrimitive{9.7290000, -0.1243150},
                AOPrimitive{4.2280000, 0.0999648},
                AOPrimitive{1.9690000, 0.4170800},
                AOPrimitive{0.8890000, 0.4751230},
                AOPrimitive{0.3964000, 0.1632680},
              },
              AOShell{
                0,
                AOPrimitive{1224000.0000000, 0.0000002},
                AOPrimitive{183200.0000000, 0.0000014},
                AOPrimitive{41700.0000000, 0.0000072},
                AOPrimitive{11810.0000000, 0.0000303},
                AOPrimitive{3853.0000000, 0.0001108},
                AOPrimitive{1391.0000000, 0.0003586},
                AOPrimitive{542.5000000, 0.0010627},
                AOPrimitive{224.9000000, 0.0028269},
                AOPrimitive{97.9300000, 0.0067674},
                AOPrimitive{44.3100000, 0.0136480},
                AOPrimitive{20.6500000, 0.0222814},
                AOPrimitive{9.7290000, 0.0196011},
                AOPrimitive{4.2280000, -0.0167708},
                AOPrimitive{1.9690000, -0.0773734},
                AOPrimitive{0.8890000, -0.1135010},
                AOPrimitive{0.3964000, -0.1391300},
              },
              AOShell{
                0,
                AOPrimitive{0.0699300, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0328900, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0161200, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0050000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{3.7649450, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{413.4000000, 0.0009082},
                AOPrimitive{97.9800000, 0.0074177},
                AOPrimitive{31.3700000, 0.0357464},
                AOPrimitive{11.6200000, 0.1185200},
                AOPrimitive{4.6710000, 0.2614030},
                AOPrimitive{1.9180000, 0.3783950},
                AOPrimitive{0.7775000, 0.3346320},
                AOPrimitive{0.3013000, 0.1268440},
                AOPrimitive{0.2275000, -0.0147117},
              },
              AOShell{
                1,
                AOPrimitive{413.4000000, -0.0000902},
                AOPrimitive{97.9800000, -0.0007393},
                AOPrimitive{31.3700000, -0.0035731},
                AOPrimitive{11.6200000, -0.0120142},
                AOPrimitive{4.6710000, -0.0267178},
                AOPrimitive{1.9180000, -0.0392753},
                AOPrimitive{0.7775000, -0.0376083},
                AOPrimitive{0.3013000, -0.0433228},
                AOPrimitive{0.2275000, 0.0518003},
              },
              AOShell{
                1,
                AOPrimitive{0.0752700, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0312600, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0134200, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0072000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.7968140, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{3.0511000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.1456650, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0517890, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0916340, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.1621360, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{5.4205850, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1341970, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.0695240, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{4.5575240, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(12): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{327600.0000000, 0.0000310},
                AOPrimitive{49050.0000000, 0.0002410},
                AOPrimitive{11150.0000000, 0.0012666},
                AOPrimitive{3152.0000000, 0.0053336},
                AOPrimitive{1025.0000000, 0.0190770},
                AOPrimitive{368.8000000, 0.0588058},
                AOPrimitive{143.2000000, 0.1514540},
                AOPrimitive{58.9600000, 0.3007160},
                AOPrimitive{25.4000000, 0.3811490},
                AOPrimitive{11.1500000, 0.2135840},
                AOPrimitive{4.0040000, 0.0231210},
                AOPrimitive{1.7010000, -0.0023076},
                AOPrimitive{0.7060000, 0.0012890},
              },
              AOShell{
                0,
                AOPrimitive{327600.0000000, -0.0000078},
                AOPrimitive{49050.0000000, -0.0000608},
                AOPrimitive{11150.0000000, -0.0003212},
                AOPrimitive{3152.0000000, -0.0013496},
                AOPrimitive{1025.0000000, -0.0049057},
                AOPrimitive{368.8000000, -0.0153561},
                AOPrimitive{143.2000000, -0.0423409},
                AOPrimitive{58.9600000, -0.0940603},
                AOPrimitive{25.4000000, -0.1634250},
                AOPrimitive{11.1500000, -0.1247540},
                AOPrimitive{4.0040000, 0.2356230},
                AOPrimitive{1.7010000, 0.5775630},
                AOPrimitive{0.7060000, 0.3352320},
              },
              AOShell{
                0,
                AOPrimitive{327600.0000000, 0.0000015},
                AOPrimitive{49050.0000000, 0.0000117},
                AOPrimitive{11150.0000000, 0.0000619},
                AOPrimitive{3152.0000000, 0.0002601},
                AOPrimitive{1025.0000000, 0.0009462},
                AOPrimitive{368.8000000, 0.0029660},
                AOPrimitive{143.2000000, 0.0082125},
                AOPrimitive{58.9600000, 0.0183977},
                AOPrimitive{25.4000000, 0.0326657},
                AOPrimitive{11.1500000, 0.0257315},
                AOPrimitive{4.0040000, -0.0535351},
                AOPrimitive{1.7010000, -0.1568950},
                AOPrimitive{0.7060000, -0.2066590},
              },
              AOShell{
                0,
                AOPrimitive{0.1410000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0680800, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0306300, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0109000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{5.4259480, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{539.6000000, 0.0008340},
                AOPrimitive{127.9000000, 0.0068922},
                AOPrimitive{41.0200000, 0.0337874},
                AOPrimitive{15.2500000, 0.1144010},
                AOPrimitive{6.1660000, 0.2595140},
                AOPrimitive{2.5610000, 0.3850950},
                AOPrimitive{1.0600000, 0.3353730},
                AOPrimitive{0.4176000, 0.1106410},
                AOPrimitive{0.2690000, -0.0121315},
              },
              AOShell{
                1,
                AOPrimitive{539.6000000, -0.0001321},
                AOPrimitive{127.9000000, -0.0010954},
                AOPrimitive{41.0200000, -0.0053950},
                AOPrimitive{15.2500000, -0.0185572},
                AOPrimitive{6.1660000, -0.0427375},
                AOPrimitive{2.5610000, -0.0647684},
                AOPrimitive{1.0600000, -0.0627818},
                AOPrimitive{0.4176000, -0.0244912},
                AOPrimitive{0.2690000, 0.1047610},
              },
              AOShell{
                1,
                AOPrimitive{0.1223000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0547600, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0238800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0081000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{2.8126150, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.9370220, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.8375060, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2883070, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.1510850, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.0774490, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{7.6689280, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.2257910, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1091400, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{5.5204730, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(13): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{419600.0000000, 0.0000278},
                AOPrimitive{62830.0000000, 0.0002163},
                AOPrimitive{14290.0000000, 0.0011375},
                AOPrimitive{4038.0000000, 0.0047963},
                AOPrimitive{1312.0000000, 0.0172389},
                AOPrimitive{470.5000000, 0.0538066},
                AOPrimitive{181.8000000, 0.1413260},
                AOPrimitive{74.4600000, 0.2892680},
                AOPrimitive{31.9000000, 0.3848250},
                AOPrimitive{13.9600000, 0.2328520},
                AOPrimitive{5.1800000, 0.0293330},
                AOPrimitive{2.2650000, -0.0030057},
                AOPrimitive{0.9664000, 0.0016667},
              },
              AOShell{
                0,
                AOPrimitive{419600.0000000, -0.0000072},
                AOPrimitive{62830.0000000, -0.0000562},
                AOPrimitive{14290.0000000, -0.0002965},
                AOPrimitive{4038.0000000, -0.0012491},
                AOPrimitive{1312.0000000, -0.0045510},
                AOPrimitive{470.5000000, -0.0144393},
                AOPrimitive{181.8000000, -0.0403464},
                AOPrimitive{74.4600000, -0.0922618},
                AOPrimitive{31.9000000, -0.1645100},
                AOPrimitive{13.9600000, -0.1412960},
                AOPrimitive{5.1800000, 0.1953650},
                AOPrimitive{2.2650000, 0.5724750},
                AOPrimitive{0.9664000, 0.3740410},
              },
              AOShell{
                0,
                AOPrimitive{419600.0000000, 0.0000017},
                AOPrimitive{62830.0000000, 0.0000130},
                AOPrimitive{14290.0000000, 0.0000685},
                AOPrimitive{4038.0000000, 0.0002883},
                AOPrimitive{1312.0000000, 0.0010528},
                AOPrimitive{470.5000000, 0.0033388},
                AOPrimitive{181.8000000, 0.0093922},
                AOPrimitive{74.4600000, 0.0216047},
                AOPrimitive{31.9000000, 0.0395873},
                AOPrimitive{13.9600000, 0.0349180},
                AOPrimitive{5.1800000, -0.0528415},
                AOPrimitive{2.2650000, -0.1918780},
                AOPrimitive{0.9664000, -0.2541150},
              },
              AOShell{
                0,
                AOPrimitive{0.2447000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1184000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0502100, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0183000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{9.0547890, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{891.3000000, 0.0004918},
                AOPrimitive{211.3000000, 0.0041584},
                AOPrimitive{68.2800000, 0.0212538},
                AOPrimitive{25.7000000, 0.0764058},
                AOPrimitive{10.6300000, 0.1942770},
                AOPrimitive{4.6020000, 0.3344280},
                AOPrimitive{2.0150000, 0.3750260},
                AOPrimitive{0.8706000, 0.2040410},
              },
              AOShell{
                1,
                AOPrimitive{891.3000000, -0.0000889},
                AOPrimitive{211.3000000, -0.0007458},
                AOPrimitive{68.2800000, -0.0038703},
                AOPrimitive{25.7000000, -0.0139350},
                AOPrimitive{10.6300000, -0.0366860},
                AOPrimitive{4.6020000, -0.0627797},
                AOPrimitive{2.0150000, -0.0789602},
                AOPrimitive{0.8706000, -0.0288589},
              },
              AOShell{
                1,
                AOPrimitive{0.2972000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1100000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0398900, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0121000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{2.5252000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{8.7733010, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{3.0211000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.6461000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2586000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.1035000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{11.6467380, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.4802000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.1538000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{6.4428330, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(14): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{513000.0000000, 0.0000261},
                AOPrimitive{76820.0000000, 0.0002029},
                AOPrimitive{17470.0000000, 0.0010671},
                AOPrimitive{4935.0000000, 0.0045060},
                AOPrimitive{1602.0000000, 0.0162359},
                AOPrimitive{574.1000000, 0.0508913},
                AOPrimitive{221.5000000, 0.1351550},
                AOPrimitive{90.5400000, 0.2812920},
                AOPrimitive{38.7400000, 0.3853360},
                AOPrimitive{16.9500000, 0.2456510},
                AOPrimitive{6.4520000, 0.0343145},
                AOPrimitive{2.8740000, -0.0033488},
                AOPrimitive{1.2500000, 0.0018762},
              },
              AOShell{
                0,
                AOPrimitive{513000.0000000, -0.0000069},
                AOPrimitive{76820.0000000, -0.0000540},
                AOPrimitive{17470.0000000, -0.0002847},
                AOPrimitive{4935.0000000, -0.0012020},
                AOPrimitive{1602.0000000, -0.0043840},
                AOPrimitive{574.1000000, -0.0139776},
                AOPrimitive{221.5000000, -0.0393516},
                AOPrimitive{90.5400000, -0.0914283},
                AOPrimitive{38.7400000, -0.1656090},
                AOPrimitive{16.9500000, -0.1525050},
                AOPrimitive{6.4520000, 0.1685240},
                AOPrimitive{2.8740000, 0.5692840},
                AOPrimitive{1.2500000, 0.3980560},
              },
              AOShell{
                0,
                AOPrimitive{513000.0000000, 0.0000018},
                AOPrimitive{76820.0000000, 0.0000138},
                AOPrimitive{17470.0000000, 0.0000730},
                AOPrimitive{4935.0000000, 0.0003077},
                AOPrimitive{1602.0000000, 0.0011256},
                AOPrimitive{574.1000000, 0.0035844},
                AOPrimitive{221.5000000, 0.0101728},
                AOPrimitive{90.5400000, 0.0237520},
                AOPrimitive{38.7400000, 0.0443483},
                AOPrimitive{16.9500000, 0.0419041},
                AOPrimitive{6.4520000, -0.0502504},
                AOPrimitive{2.8740000, -0.2165780},
                AOPrimitive{1.2500000, -0.2864480},
              },
              AOShell{
                0,
                AOPrimitive{0.3599000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1699000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0706600, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0275000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{9.6116850, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1122.0000000, 0.0004481},
                AOPrimitive{266.0000000, 0.0038164},
                AOPrimitive{85.9200000, 0.0198105},
                AOPrimitive{32.3300000, 0.0727017},
                AOPrimitive{13.3700000, 0.1898390},
                AOPrimitive{5.8000000, 0.3356720},
                AOPrimitive{2.5590000, 0.3793650},
                AOPrimitive{1.1240000, 0.2011930},
              },
              AOShell{
                1,
                AOPrimitive{1122.0000000, -0.0000965},
                AOPrimitive{266.0000000, -0.0008120},
                AOPrimitive{85.9200000, -0.0043009},
                AOPrimitive{32.3300000, -0.0157502},
                AOPrimitive{13.3700000, -0.0429541},
                AOPrimitive{5.8000000, -0.0752574},
                AOPrimitive{2.5590000, -0.0971446},
                AOPrimitive{1.1240000, -0.0227507},
              },
              AOShell{
                1,
                AOPrimitive{0.3988000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1533000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0572800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0200000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{3.5478000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{11.9496930, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{4.3232000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.9591000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.3560000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.1394000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{16.3016750, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.6227000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.2141000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{7.6783760, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(15): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{615200.0000000, 0.0000247},
                AOPrimitive{92120.0000000, 0.0001925},
                AOPrimitive{20950.0000000, 0.0010120},
                AOPrimitive{5920.0000000, 0.0042726},
                AOPrimitive{1922.0000000, 0.0154161},
                AOPrimitive{688.0000000, 0.0485976},
                AOPrimitive{265.0000000, 0.1300600},
                AOPrimitive{108.2000000, 0.2745140},
                AOPrimitive{46.2200000, 0.3854020},
                AOPrimitive{20.2300000, 0.2559340},
                AOPrimitive{7.8590000, 0.0391237},
                AOPrimitive{3.5470000, -0.0036801},
                AOPrimitive{1.5640000, 0.0020821},
              },
              AOShell{
                0,
                AOPrimitive{615200.0000000, -0.0000067},
                AOPrimitive{92120.0000000, -0.0000522},
                AOPrimitive{20950.0000000, -0.0002754},
                AOPrimitive{5920.0000000, -0.0011631},
                AOPrimitive{1922.0000000, -0.0042428},
                AOPrimitive{688.0000000, -0.0136114},
                AOPrimitive{265.0000000, -0.0385114},
                AOPrimitive{108.2000000, -0.0906643},
                AOPrimitive{46.2200000, -0.1665840},
                AOPrimitive{20.2300000, -0.1614470},
                AOPrimitive{7.8590000, 0.1467810},
                AOPrimitive{3.5470000, 0.5666820},
                AOPrimitive{1.5640000, 0.4164330},
              },
              AOShell{
                0,
                AOPrimitive{615200.0000000, 0.0000018},
                AOPrimitive{92120.0000000, 0.0000143},
                AOPrimitive{20950.0000000, 0.0000757},
                AOPrimitive{5920.0000000, 0.0003192},
                AOPrimitive{1922.0000000, 0.0011685},
                AOPrimitive{688.0000000, 0.0037427},
                AOPrimitive{265.0000000, 0.0106817},
                AOPrimitive{108.2000000, 0.0252657},
                AOPrimitive{46.2200000, 0.0479283},
                AOPrimitive{20.2300000, 0.0477096},
                AOPrimitive{7.8590000, -0.0466525},
                AOPrimitive{3.5470000, -0.2349680},
                AOPrimitive{1.5640000, -0.3113370},
              },
              AOShell{
                0,
                AOPrimitive{0.4888000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.2266000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0933100, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0354000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{12.0363490, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1367.0000000, 0.0004210},
                AOPrimitive{324.0000000, 0.0036098},
                AOPrimitive{104.6000000, 0.0189217},
                AOPrimitive{39.3700000, 0.0705560},
                AOPrimitive{16.2600000, 0.1881570},
                AOPrimitive{7.0560000, 0.3387090},
                AOPrimitive{3.1300000, 0.3819430},
                AOPrimitive{1.3940000, 0.1952610},
              },
              AOShell{
                1,
                AOPrimitive{1367.0000000, -0.0001008},
                AOPrimitive{324.0000000, -0.0008545},
                AOPrimitive{104.6000000, -0.0045712},
                AOPrimitive{39.3700000, -0.0170327},
                AOPrimitive{16.2600000, -0.0475204},
                AOPrimitive{7.0560000, -0.0852786},
                AOPrimitive{3.1300000, -0.1096760},
                AOPrimitive{1.3940000, -0.0161181},
              },
              AOShell{
                1,
                AOPrimitive{0.5179000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.2032000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0769800, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0272000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{4.1823000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{13.5518980, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{6.0350000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{1.3919000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.4824000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.1820000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{22.6868180, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.7331000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.2522000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{9.0980210, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(16): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{727800.0000000, 0.0000236},
                AOPrimitive{109000.0000000, 0.0001835},
                AOPrimitive{24800.0000000, 0.0009643},
                AOPrimitive{7014.0000000, 0.0040654},
                AOPrimitive{2278.0000000, 0.0146973},
                AOPrimitive{814.7000000, 0.0465081},
                AOPrimitive{313.4000000, 0.1255080},
                AOPrimitive{127.7000000, 0.2684330},
                AOPrimitive{54.4800000, 0.3848090},
                AOPrimitive{23.8500000, 0.2653720},
                AOPrimitive{9.4280000, 0.0437326},
                AOPrimitive{4.2900000, -0.0037881},
                AOPrimitive{1.9090000, 0.0021808},
              },
              AOShell{
                0,
                AOPrimitive{727800.0000000, -0.0000065},
                AOPrimitive{109000.0000000, -0.0000507},
                AOPrimitive{24800.0000000, -0.0002668},
                AOPrimitive{7014.0000000, -0.0011260},
                AOPrimitive{2278.0000000, -0.0041119},
                AOPrimitive{814.7000000, -0.0132454},
                AOPrimitive{313.4000000, -0.0377004},
                AOPrimitive{127.7000000, -0.0898554},
                AOPrimitive{54.4800000, -0.1670980},
                AOPrimitive{23.8500000, -0.1693540},
                AOPrimitive{9.4280000, 0.1278240},
                AOPrimitive{4.2900000, 0.5648620},
                AOPrimitive{1.9090000, 0.4317670},
              },
              AOShell{
                0,
                AOPrimitive{727800.0000000, 0.0000019},
                AOPrimitive{109000.0000000, 0.0000147},
                AOPrimitive{24800.0000000, 0.0000775},
                AOPrimitive{7014.0000000, 0.0003265},
                AOPrimitive{2278.0000000, 0.0011969},
                AOPrimitive{814.7000000, 0.0038480},
                AOPrimitive{313.4000000, 0.0110539},
                AOPrimitive{127.7000000, 0.0264645},
                AOPrimitive{54.4800000, 0.0508771},
                AOPrimitive{23.8500000, 0.0530030},
                AOPrimitive{9.4280000, -0.0425518},
                AOPrimitive{4.2900000, -0.2508530},
                AOPrimitive{1.9090000, -0.3331520},
              },
              AOShell{
                0,
                AOPrimitive{0.6270000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.2873000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1172000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0428000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{12.5949320, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1546.0000000, 0.0004412},
                AOPrimitive{366.4000000, 0.0037757},
                AOPrimitive{118.4000000, 0.0198360},
                AOPrimitive{44.5300000, 0.0742063},
                AOPrimitive{18.3800000, 0.1973270},
                AOPrimitive{7.9650000, 0.3518510},
                AOPrimitive{3.5410000, 0.3786870},
                AOPrimitive{1.5910000, 0.1709310},
              },
              AOShell{
                1,
                AOPrimitive{1546.0000000, -0.0001131},
                AOPrimitive{366.4000000, -0.0009586},
                AOPrimitive{118.4000000, -0.0051347},
                AOPrimitive{44.5300000, -0.0192641},
                AOPrimitive{18.3800000, -0.0535980},
                AOPrimitive{7.9650000, -0.0960333},
                AOPrimitive{3.5410000, -0.1181830},
                AOPrimitive{1.5910000, 0.0092319},
              },
              AOShell{
                1,
                AOPrimitive{0.6205000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.2420000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0901400, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0317000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{5.0019000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{15.8646850, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{8.7486000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{2.0766000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.6044000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2199000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{33.1306190, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.7628000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.2776000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{10.5039430, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(17): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{834900.0000000, 0.0000232},
                AOPrimitive{125000.0000000, 0.0001802},
                AOPrimitive{28430.0000000, 0.0009478},
                AOPrimitive{8033.0000000, 0.0040014},
                AOPrimitive{2608.0000000, 0.0144629},
                AOPrimitive{933.9000000, 0.0456586},
                AOPrimitive{360.0000000, 0.1232480},
                AOPrimitive{147.0000000, 0.2643690},
                AOPrimitive{62.8800000, 0.3829890},
                AOPrimitive{27.6000000, 0.2709340},
                AOPrimitive{11.0800000, 0.0471404},
                AOPrimitive{5.0750000, -0.0037177},
                AOPrimitive{2.2780000, 0.0021916},
              },
              AOShell{
                0,
                AOPrimitive{834900.0000000, -0.0000065},
                AOPrimitive{125000.0000000, -0.0000505},
                AOPrimitive{28430.0000000, -0.0002661},
                AOPrimitive{8033.0000000, -0.0011250},
                AOPrimitive{2608.0000000, -0.0041050},
                AOPrimitive{933.9000000, -0.0131987},
                AOPrimitive{360.0000000, -0.0375342},
                AOPrimitive{147.0000000, -0.0897233},
                AOPrimitive{62.8800000, -0.1676710},
                AOPrimitive{27.6000000, -0.1747630},
                AOPrimitive{11.0800000, 0.1149090},
                AOPrimitive{5.0750000, 0.5636180},
                AOPrimitive{2.2780000, 0.4416060},
              },
              AOShell{
                0,
                AOPrimitive{834900.0000000, 0.0000020},
                AOPrimitive{125000.0000000, 0.0000153},
                AOPrimitive{28430.0000000, 0.0000806},
                AOPrimitive{8033.0000000, 0.0003400},
                AOPrimitive{2608.0000000, 0.0012455},
                AOPrimitive{933.9000000, 0.0039961},
                AOPrimitive{360.0000000, 0.0114751},
                AOPrimitive{147.0000000, 0.0275504},
                AOPrimitive{62.8800000, 0.0532917},
                AOPrimitive{27.6000000, 0.0571246},
                AOPrimitive{11.0800000, -0.0395201},
                AOPrimitive{5.0750000, -0.2643430},
                AOPrimitive{2.2780000, -0.3492910},
              },
              AOShell{
                0,
                AOPrimitive{0.7775000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.3527000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1431000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0519000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{13.9643830, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1703.0000000, 0.0004740},
                AOPrimitive{403.6000000, 0.0040641},
                AOPrimitive{130.3000000, 0.0213355},
                AOPrimitive{49.0500000, 0.0794611},
                AOPrimitive{20.2600000, 0.2089270},
                AOPrimitive{8.7870000, 0.3649450},
                AOPrimitive{3.9190000, 0.3717250},
                AOPrimitive{1.7650000, 0.1462920},
              },
              AOShell{
                1,
                AOPrimitive{1703.0000000, -0.0001283},
                AOPrimitive{403.6000000, -0.0010936},
                AOPrimitive{130.3000000, -0.0058343},
                AOPrimitive{49.0500000, -0.0219258},
                AOPrimitive{20.2600000, -0.0601385},
                AOPrimitive{8.7870000, -0.1069290},
                AOPrimitive{3.9190000, -0.1224540},
                AOPrimitive{1.7650000, 0.0383619},
              },
              AOShell{
                1,
                AOPrimitive{0.7207000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.2839000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1060000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0376000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{5.6488000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{17.5607860, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{10.3990000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{2.4101000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.6664000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2442000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{39.5140510, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.8662000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.3289000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{12.1867620, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        case(18): {
            return AOBasisSet{
              AOShell{
                0,
                AOPrimitive{950600.0000000, 0.0000228},
                AOPrimitive{142300.0000000, 0.0001769},
                AOPrimitive{32360.0000000, 0.0009313},
                AOPrimitive{9145.0000000, 0.0039286},
                AOPrimitive{2970.0000000, 0.0142064},
                AOPrimitive{1064.0000000, 0.0448114},
                AOPrimitive{410.8000000, 0.1210010},
                AOPrimitive{168.0000000, 0.2605790},
                AOPrimitive{71.9900000, 0.3813640},
                AOPrimitive{31.6700000, 0.2760580},
                AOPrimitive{12.8900000, 0.0505179},
                AOPrimitive{5.9290000, -0.0035987},
                AOPrimitive{2.6780000, 0.0021880},
              },
              AOShell{
                0,
                AOPrimitive{950600.0000000, -0.0000065},
                AOPrimitive{142300.0000000, -0.0000502},
                AOPrimitive{32360.0000000, -0.0002648},
                AOPrimitive{9145.0000000, -0.0011190},
                AOPrimitive{2970.0000000, -0.0040828},
                AOPrimitive{1064.0000000, -0.0131216},
                AOPrimitive{410.8000000, -0.0372855},
                AOPrimitive{168.0000000, -0.0894709},
                AOPrimitive{71.9900000, -0.1680540},
                AOPrimitive{31.6700000, -0.1795940},
                AOPrimitive{12.8900000, 0.1029530},
                AOPrimitive{5.9290000, 0.5626300},
                AOPrimitive{2.6780000, 0.4503550},
              },
              AOShell{
                0,
                AOPrimitive{950600.0000000, 0.0000020},
                AOPrimitive{142300.0000000, 0.0000157},
                AOPrimitive{32360.0000000, 0.0000829},
                AOPrimitive{9145.0000000, 0.0003493},
                AOPrimitive{2970.0000000, 0.0012798},
                AOPrimitive{1064.0000000, 0.0041037},
                AOPrimitive{410.8000000, 0.0117789},
                AOPrimitive{168.0000000, 0.0283868},
                AOPrimitive{71.9900000, 0.0552406},
                AOPrimitive{31.6700000, 0.0607492},
                AOPrimitive{12.8900000, -0.0362012},
                AOPrimitive{5.9290000, -0.2753980},
                AOPrimitive{2.6780000, -0.3628450},
              },
              AOShell{
                0,
                AOPrimitive{0.9416000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.4239000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.1714000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{0.0610000, 1.0000000},
              },
              AOShell{
                0,
                AOPrimitive{20.2316380, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{1890.0000000, 0.0004958},
                AOPrimitive{447.8000000, 0.0042517},
                AOPrimitive{144.6000000, 0.0223277},
                AOPrimitive{54.4600000, 0.0830878},
                AOPrimitive{22.5100000, 0.2171100},
                AOPrimitive{9.7740000, 0.3745070},
                AOPrimitive{4.3680000, 0.3664450},
                AOPrimitive{1.9590000, 0.1292450},
              },
              AOShell{
                1,
                AOPrimitive{1890.0000000, -0.0001389},
                AOPrimitive{447.8000000, -0.0011887},
                AOPrimitive{144.6000000, -0.0063255},
                AOPrimitive{54.4600000, -0.0238813},
                AOPrimitive{22.5100000, -0.0649238},
                AOPrimitive{9.7740000, -0.1154440},
                AOPrimitive{4.3680000, -0.1236510},
                AOPrimitive{1.9590000, 0.0649055},
              },
              AOShell{
                1,
                AOPrimitive{0.8260000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.3297000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.1242000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{0.0435000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{6.3209000, 1.0000000},
              },
              AOShell{
                1,
                AOPrimitive{19.5376940, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{12.6860000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{3.0405000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.8085000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{0.2864000, 1.0000000},
              },
              AOShell{
                2,
                AOPrimitive{48.6811040, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{1.1691000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{0.4006000, 1.0000000},
              },
              AOShell{
                3,
                AOPrimitive{13.6122650, 1.0000000},
              },
            }; // End AOBasis
        }      // End case
        default: { throw std::out_of_range("Basis not available for Z"); }
    } // end switch

} // end function
} // namespace libchemist::detail_
