/*
 * This file is autogenerated by generate_basis.py.  Any modifications made in
 * this file will be lost next time generate_basis.py is run.
 */

#include "libchemist/defaults/nwx_basis_list.hpp"

namespace libchemist::detail_ {

Center<double> aug_dash_cc_dash_pv5z_diffuse(std::size_t Z) {
    switch(Z) {
        case(1): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0207000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0744000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.1560000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.2740000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.5430000});
            return rv;
        } // End case
        case(2): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0466400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.1400000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.2892000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.5345000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.7899000});
            return rv;
        } // End case
        case(3): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{6.100000e-03});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{6.500000e-03});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{2.350000e-02});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{4.480000e-02});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{7.240000e-02});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.274000e-01});
            return rv;
        } // End case
        case(4): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.280000e-02});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{7.600000e-03});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{4.280000e-02});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{7.190000e-02});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{9.790000e-02});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{2.033000e-01});
            return rv;
        } // End case
        case(5): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0261000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0157000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0431000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0843000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.2020000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.3840000});
            return rv;
        } // End case
        case(6): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0394000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0272000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0701000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1380000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.3190000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.5860000});
            return rv;
        } // End case
        case(7): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0518000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0369000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0971000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1920000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.4360000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.7880000});
            return rv;
        } // End case
        case(8): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0655000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0446000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.1310000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.2370000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.5170000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.0240000});
            return rv;
        } // End case
        case(9): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0806000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0550000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.1720000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.3310000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.6630000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.3260000});
            return rv;
        } // End case
        case(10): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0957000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0654000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.2130000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.4250000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.8090000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.6280000});
            return rv;
        } // End case
        case(11): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{5.100000e-03});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{5.500000e-03});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{2.290000e-02});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{4.140000e-02});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{7.320000e-02});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.048000e-01});
            return rv;
        } // End case
        case(12): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{1.080000e-02});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{7.100000e-03});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{3.710000e-02});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{5.790000e-02});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{9.470000e-02});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.577000e-01});
            return rv;
        } // End case
        case(13): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0177000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0115000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0294000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0509000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1069000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.2270000});
            return rv;
        } // End case
        case(14): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0260000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0192000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0468000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0735000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1510000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.3230000});
            return rv;
        } // End case
        case(15): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0335000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0253000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0624000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0950000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1840000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.3720000});
            return rv;
        } // End case
        case(16): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0420000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0294000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0794000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1188000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.2200000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.4720000});
            return rv;
        } // End case
        case(17): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0479000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0348000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.1003000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1640000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.2770000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.6070000});
            return rv;
        } // End case
        case(18): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0538000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0402000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.1210000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.2090000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.3340000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.7420000});
            return rv;
        } // End case
        case(21): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0100700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0100800});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0089500});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0248200});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.0488400});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.0948900});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{0.1386300});
            return rv;
        } // End case
        case(22): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0104800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0108700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0112700});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0408400});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.0794900});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.1678700});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{0.3208900});
            return rv;
        } // End case
        case(23): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0110500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0115100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0141300});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0581200});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1189300});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.2504200});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{0.5895900});
            return rv;
        } // End case
        case(24): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0115100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0121200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0166900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0710200});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1482600});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.3265100});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{0.8588900});
            return rv;
        } // End case
        case(25): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0118300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0126100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0184500});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0875300});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1925300});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.4178700});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{1.1122100});
            return rv;
        } // End case
        case(26): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0122900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0127900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0204400});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1066600});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.2453900});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.5286200});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{1.4049900});
            return rv;
        } // End case
        case(27): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0129000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0139000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0214100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1265500});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.2974800});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.6387800});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{1.7051400});
            return rv;
        } // End case
        case(28): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0132200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0135600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0243000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1538800});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.3682800});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.7879800});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{2.1037100});
            return rv;
        } // End case
        case(29): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0138900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0139300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0419500});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1733900});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.4263700});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.9050900});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{2.4474100});
            return rv;
        } // End case
        case(30): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0145100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0141500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0566100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.2010100});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.4613900});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{1.0655400});
            rv.add_shell(ShellType::pure, 6, std::vector<double>{1.0000000},
                         std::vector<double>{2.7941400});
            return rv;
        } // End case
        case(31): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0173010});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0110500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0260000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0511000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1140000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.2540000});
            return rv;
        } // End case
        case(32): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0242740});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0175930});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0364000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0705000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1460000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.3200000});
            return rv;
        } // End case
        case(33): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0294180});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0220430});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0488000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0899000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1655000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.3668000});
            return rv;
        } // End case
        case(34): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0339350});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0249750});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0548000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.0992000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.1830000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.4020000});
            return rv;
        } // End case
        case(35): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0391060});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0290520});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.0781000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1388000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.2190000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.4910000});
            return rv;
        } // End case
        case(36): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000},
                         std::vector<double>{0.0442770});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000},
                         std::vector<double>{0.0331290});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000},
                         std::vector<double>{0.1014000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000},
                         std::vector<double>{0.1784000});
            rv.add_shell(ShellType::pure, 4, std::vector<double>{1.0000000},
                         std::vector<double>{0.2550000});
            rv.add_shell(ShellType::pure, 5, std::vector<double>{1.0000000},
                         std::vector<double>{0.5800000});
            return rv;
        } // End case
        default: {
            throw std::out_of_range("Basis not available for Z");
        }
    } // end switch

} // end function
} // namespace libchemist::detail_