/*
 * This file is autogenerated by generate_basis.py.  Any modifications made in
 * this file will be lost next time generate_basis.py is run.
 */

#include "libchemist/defaults/nwx_basis_list.hpp"

namespace libchemist::detail_ {

Center<double> cc_dash_pvdz_dash_jkfit(std::size_t Z) {
    switch(Z) {
        case(1): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{9.5302493300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.9174506200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6842404900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2841325600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.9133232000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2621205400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5019977600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.3135329100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7129072400});
            return rv;
        } // End case
        case(5): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{441.8891315700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{92.0696297900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{29.9784485200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{11.4263307900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.3808722400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.0594033500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.9011571800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5245528900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2463472600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1208580600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{229.9511519500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{36.3816947600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{12.1197967000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{3.8441129400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1002761200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3973311800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1351476500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{9.3643373900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{3.1035658000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2006835100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4082962500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1318830400});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7235912400});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2615912400});
            return rv;
        } // End case
        case(6): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1113.9867719000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{369.1623418000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{121.7927523200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{48.1271145400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{20.3650740000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{8.0883596900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.5068656600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2438537400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4844990000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1918516000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{102.9917624900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{28.1325940100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{9.8364318200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{3.3490545000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.4947618600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5769010900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2032006300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{10.5940683600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{3.5997195400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3355691100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5194976500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1995412500});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1948663400});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4158663400});
            return rv;
        } // End case
        case(7): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1102.8622453000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{370.9804115300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{136.7355593800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{50.7558719200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{20.5356561000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{7.8318737200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{3.4784063900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.4552856600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6306898900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2727659600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{93.5409540700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{29.5240195300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{10.9175029900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{4.3449289000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.8216912600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7579242400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2824146900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{16.4193789300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{5.0104049400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.9793971900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7849577200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2895406600});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.7935424000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6085424000});
            return rv;
        } // End case
        case(8): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1517.8667506000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{489.6795200800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{176.7211866500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{63.7922331400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{25.3664991300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{9.9135491200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.4645306600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.8017743700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8078971100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3386432700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{120.1603092100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{34.4096224700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{12.5811486100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{5.0663824200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.0346927100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8609296700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3668135700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{19.0430628100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{5.8060381100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.1891841600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8779461400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3562364700});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{2.4939147900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8249147900});
            return rv;
        } // End case
        case(9): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1885.0661216000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{623.7558229700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{227.9240502900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{82.1841787700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{32.6289375800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{12.7832795800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{5.6589257900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.3208306700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.0191520900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4219669900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{153.7206976800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{45.3904508700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{16.7858457700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{6.7293857800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.6694607000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1049787100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4572770400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{24.8696853500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{7.5554441600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.8268499200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1123341300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4387775400});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{3.3353964000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.0833964000});
            return rv;
        } // End case
        case(10): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2252.2655000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{757.8321000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{279.1269000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{100.5761000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{39.8914000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{15.6530000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{6.8533000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.8399000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2304000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5053000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{187.2811000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{56.3713000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{20.9905000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{8.3924000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{3.3042000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3490000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5477000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{30.6963000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{9.3049000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{3.4645000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3467000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5213000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{4.1769000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3419000000});
            return rv;
        } // End case
        case(13): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{3155.1928168000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{804.8182484300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{278.2871627900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{106.7394703400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{44.7260545500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{19.9859816200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{8.2139836400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.1826731600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.0606294400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1394540100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3532161100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2151205200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.0910011200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{472.1639702800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{132.2032913200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{50.4601665400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{21.1311243100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{10.4579550800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{4.9925589400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.4609220800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.0708266200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4186224200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2441845400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1182475300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{95.3743909700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{31.1377151000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{13.0324653000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{6.0372010600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.9357330000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.4175558600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5338715700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2554566900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1084345600});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3718899700});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3919685600});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1679685600});
            return rv;
        } // End case
        case(14): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{3966.7823006000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{913.6524013000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{309.4757253200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{121.4837189600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{51.9498425400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{22.5314152600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{8.6118544500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.0353794600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.5605354300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8265834400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4840347100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2875787000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1318818800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{629.3068073700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{255.7150091400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{109.2963066400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{45.9437697600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{19.7842269400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{9.7746090300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{4.6426781700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.0449974100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8220814400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4097874100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1845146600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{181.6734461400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{59.6544149200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{25.3539836100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{11.7189735300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{5.4455778100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.4659440000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.0365292700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4109700100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1695006800});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.9560745600});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5588784500});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2368784500});
            return rv;
        } // End case
        case(15): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{5107.3657113000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1086.7632676000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{350.6367404300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{136.6570875000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{58.9922085400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{25.6521241800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{9.8584341800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.6827641200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.9275607000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.0059954100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5881247300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3413198400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1800299900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{575.5625546500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{162.6403613000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{62.4338916000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{26.3873934900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{13.0778851200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{6.2324334300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.6964172000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.5942218900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8899947300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4895507900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2308329000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{202.1945107100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{60.1415843700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{24.1167628700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{11.0295862600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{5.3635229000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.6589552200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1768422300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4953730000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2104297800});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{2.6399317600});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7542662200});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3182662200});
            return rv;
        } // End case
        case(16): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{6402.4580816000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1704.9249408000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{598.0903890400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{225.9092036400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{94.4262619100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{37.2224208400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{18.2591065300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{8.7937857300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.4619424700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.2735987700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7807539500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4819115400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2157355500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{796.1648161800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{226.1792826600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{85.5986457600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{36.2689783800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{16.3252070000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{7.6145421600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{3.3388130000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.8665221500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.9402516000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5152125600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2631838000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{190.5565867200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{60.3468014300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{25.1419670600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{12.1467682000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{6.2993488100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{3.0706106700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2911977800});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5667860300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2419241900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{3.3096133000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.9456038000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3956038000});
            return rv;
        } // End case
        case(17): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{7082.7970581000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2109.3095076000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{768.4128187300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{284.7925541600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{116.5533173100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{46.3948209900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{21.9563033900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{9.9930272100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.7199459600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.6573396200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.0813481100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5315467900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2336703900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{973.7352850900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{278.9910934700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{105.8864451600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{45.2318468800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{20.2891661500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{9.5829383800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{4.4641678600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.3625612100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1491964200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6031021700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3059091100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{204.3803006300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{63.6938933100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{25.7266689800});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{11.6024672700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{5.4574541500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.8838397600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3394023600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6164922200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2747014300});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{4.2040664000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2011618300});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4991618300});
            return rv;
        } // End case
        case(18): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{7763.1360000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2513.6941000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{938.7352000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{343.6759000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{138.6804000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{55.5672000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{25.6535000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{11.1923000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.9779000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{3.0411000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3819000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5812000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2516000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1151.3058000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{331.8029000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{126.1742000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{54.1947000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{24.2531000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{11.5513000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{5.5895000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.8586000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3581000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6910000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3486000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{218.2040000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{67.0410000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{26.3114000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{11.0582000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{4.6156000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.6971000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3876000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6662000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3075000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{5.0985000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.4567000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6027000000});
            return rv;
        } // End case
        case(31): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.1272831300, 0.3720453100, 0.8384066400},
              std::vector<double>{24344.9203460000, 6136.1607523000,
                                  2311.6328454000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{932.0505787900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{397.0842341400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{159.6033039300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{72.7848788800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{36.1137652400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{16.2435039200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{9.2825099100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{4.0058310000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.7125653200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6994488200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3967178000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1899920100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.0956339100});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.2249443100, 0.8920965200},
                         std::vector<double>{3601.8172624000, 1071.1259059000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{425.4144481300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{188.9133526400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{81.5729699600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{40.7016141600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{20.8304241000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{10.8626164800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{5.4337812300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.7269817500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2671120500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5079257400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2987859600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1354972400});
            rv.add_shell(ShellType::pure, 2,
                         std::vector<double>{0.2215749100, 0.9993745100},
                         std::vector<double>{732.4667776200, 239.2119019000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{100.0696764000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{47.2459532300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{23.7950972600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{12.0862295500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{6.0292436800});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{3.0174580800});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.4491487100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6063315300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3212535300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1266353400});
            rv.add_shell(ShellType::pure, 3,
                         std::vector<double>{0.5123927700, 1.4994319000},
                         std::vector<double>{178.2130670400, 68.0364977900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{30.9676242800});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{14.4360113700});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{7.1938511600});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{3.5671717100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.7019559200});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6657036300});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3736281900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1813212800});
            return rv;
        } // End case
        case(32): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.1068937100, 0.4034363000, 0.8994145600},
              std::vector<double>{22773.5604550000, 5000.6583126000,
                                  1592.2452139000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{603.4164358200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{250.4105598100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{114.4684331500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{51.6546979900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{25.2558794200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{13.6738059200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{5.7434289600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.9262556300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.5862260400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8603014500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4779034600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2794239800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1334504700});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.2473833100, 0.8265900500},
                         std::vector<double>{3613.1361971000, 1184.0325771000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{491.0461816900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{215.2910907800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{92.4369731700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{45.7444686500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{22.5423992900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{11.6531166800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{5.7496612000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.8520130300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3725146000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5623959900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3391684100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1714961700});
            rv.add_shell(ShellType::pure, 2,
                         std::vector<double>{0.2038319700, 0.9999454000},
                         std::vector<double>{881.9348752600, 284.4352619200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{118.2374808700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{55.4085370000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{27.2186933100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{13.5173824400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{6.6237790000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{3.2163968700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.4726690000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6124387400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3711551900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1682953400});
            rv.add_shell(ShellType::pure, 3,
                         std::vector<double>{0.5163238100, 1.5368421000},
                         std::vector<double>{195.2125225000, 74.1385939100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{33.9034860600});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{15.9737999400});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{7.9618397200});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{3.9598958100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.9207992200});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8277250900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4444660800});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2211018500});
            return rv;
        } // End case
        case(33): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.1664924200, 0.4139251900, 1.0061557000},
              std::vector<double>{29056.4496300000, 7789.3929020000,
                                  3115.0226965000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1219.4815190000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{499.4515793800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{198.6619971400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{91.4704104500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{45.4109634600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{21.6552338900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{12.2684805700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{5.3458507600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.5087512900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2426796500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6950988800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3379012700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1532617400});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.2591594700, 0.9797282800},
                         std::vector<double>{4192.9053911000, 1307.4981236000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{530.5127960500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{234.9147801700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{102.8815897700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{51.9318376300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{27.0897785500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{13.9155141700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{7.0649308400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{3.6229296800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.8016657600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7117891100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4224117100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2107457800});
            rv.add_shell(ShellType::pure, 2,
                         std::vector<double>{0.2926450300, 1.5358343000},
                         std::vector<double>{1031.1346480000, 329.7031907100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{136.4704397700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{64.1070442900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{31.9390710200});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{15.9269466600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{8.1339315000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{4.1572662300});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.0135123000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8786121000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4564261800});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2005739700});
            rv.add_shell(ShellType::pure, 3,
                         std::vector<double>{0.5459131000, 1.7642104000},
                         std::vector<double>{225.9527611600, 86.1244508800});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{39.0845955100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{18.2705841500});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{9.2240269100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{4.6658028800});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{2.3111213000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.9954822500});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4734128900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2123816300});
            return rv;
        } // End case
        case(34): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.1346807100, 0.3641358800, 0.8063588600},
              std::vector<double>{30873.0250700000, 7904.1554521000,
                                  3171.5651082000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1274.8759770000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{528.4344954200});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{212.5981330800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{98.0720082600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{49.1868497500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{23.9973568500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{13.2526764000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{5.9868255900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.9182860400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.4955683700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7507268800});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3535188100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1624226400});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.2255395500, 0.8661366300},
                         std::vector<double>{4356.7664971000, 1329.4920349000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{534.4538159900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{238.2830609500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{106.0262289000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{53.6976077600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{27.9880084500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{14.3632627700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{7.4733102000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{3.8914374500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.9695241200});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8303661400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4439438900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2338934800});
            rv.add_shell(ShellType::pure, 2,
                         std::vector<double>{0.2091937100, 1.0016519000},
                         std::vector<double>{977.4242332700, 316.1409426600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{132.7794394100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{63.2066981400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{31.6758660800});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{15.7940354400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{8.1919288400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{4.2560754100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.1290466900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.9540622100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4563163700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2058462900});
            rv.add_shell(ShellType::pure, 3,
                         std::vector<double>{0.4223567000, 1.4996628000},
                         std::vector<double>{263.6253763000, 100.5690344000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{45.2651279700});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{21.3090142900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{10.8223516300});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{5.4668236400});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{2.6727579200});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1774870100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4910105200});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1995259900});
            return rv;
        } // End case
        case(35): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(
              ShellType::pure, 0,
              std::vector<double>{0.0828192100, 0.3302447700, 0.8099979100},
              std::vector<double>{40743.5826960000, 8836.9992943000,
                                  2867.8428015000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1125.8702577000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{492.2709414500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{211.3156998100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{97.7962627100});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{51.1755943300});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{26.5077325400});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{14.4797189700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{6.6987578900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{3.3777286500});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{1.8272648600});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.8523574700});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4068756900});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.1857584100});
            rv.add_shell(ShellType::pure, 1,
                         std::vector<double>{0.2246067300, 0.8816111500},
                         std::vector<double>{4686.8414735000, 1415.2446847000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{570.4638559500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{256.2926400700});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{114.3373969500});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{58.4544696900});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{31.1409579600});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{16.1146243400});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{8.6458991000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{4.6023310100});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.3376539800});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.0026973300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5610166300});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2907778500});
            rv.add_shell(ShellType::pure, 2,
                         std::vector<double>{0.2270021800, 1.0066065000},
                         std::vector<double>{974.1444645200, 323.9343779400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{139.2352040100});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{67.8206380600});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{35.1941332900});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{18.1420696700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{9.3549795400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{4.8733310700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.4336865400});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.0950884500});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5245166700});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2375864600});
            rv.add_shell(ShellType::pure, 3,
                         std::vector<double>{0.4342843600, 1.5040121000},
                         std::vector<double>{273.5164867600, 103.4867796600});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{46.8285170300});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{22.0911704100});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{11.3066778900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{5.8509213900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{3.0030205800});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.3599193700});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.7021423900});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3538007400});
            return rv;
        } // End case
        case(36): {
            Center<double> rv(0.0, 0.0, 0.0);
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{50614.1403000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{9769.8431000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2564.1205000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{976.8645000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{456.1074000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{210.0333000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{97.5205000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{53.1643000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{29.0181000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{15.7068000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{7.4107000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{3.8372000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{2.1590000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.9540000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.4602000000});
            rv.add_shell(ShellType::pure, 0, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2091000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{5016.9164000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1500.9973000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{606.4739000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{274.3022000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{122.6486000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{63.2113000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{34.2939000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{17.8660000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{9.8185000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{5.3132000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{2.7058000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{1.1750000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.6781000000});
            rv.add_shell(ShellType::pure, 1, std::vector<double>{1.0000000000},
                         std::vector<double>{0.3477000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{970.8647000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{331.7278000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{145.6910000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{72.4346000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{38.7124000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{20.4901000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{10.5180000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{5.4906000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{2.7383000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{1.2361000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5927000000});
            rv.add_shell(ShellType::pure, 2, std::vector<double>{1.0000000000},
                         std::vector<double>{0.2693000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{283.4076000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{106.4045000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{48.3919000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{22.8733000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{11.7910000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{6.2350000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{3.3333000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{1.5424000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.9133000000});
            rv.add_shell(ShellType::pure, 3, std::vector<double>{1.0000000000},
                         std::vector<double>{0.5081000000});
            return rv;
        } // End case
        default: {
            throw std::out_of_range("Basis not available for Z");
        }
    } // end switch

} // end function
} // namespace libchemist::detail_