/*
 * This file is autogenerated by generate_densities.py.  Any modifications made
 * in this file will be lost next time generate_densities.py is run.
 */

#pragma once
#include <vector>

namespace chemist::detail_ {
std::vector<std::vector<double>> six_dash_31g_density(std::size_t Z);
std::vector<std::vector<double>> sto_dash_3g_density(std::size_t Z);
std::vector<std::vector<double>> sto_dash_6g_density(std::size_t Z);
} // namespace chemist::detail_
